include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - '**/node_modules/**'
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    unnecessary_underscores: false
    use_super_parameters: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors_in_immutables: false
    prefer_const_declarations: false
    prefer_final_fields: false
    prefer_final_locals: false
    prefer_final_in_for_each: false
    avoid_print: false
    avoid_function_literals_in_foreach_calls: false
    require_trailing_commas: false
    sort_child_properties_last: false
    sort_constructors_first: false
    sort_pub_dependencies: false
    directives_ordering: false
    always_use_package_imports: false
    cascade_invocations: false
    library_private_types_in_public_api: false
