// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-tDFTRzkrKthxTXsskFM8tBwI4au9xHI',
    appId: '1:80235878542:web:d0710da80b23e6051351df',
    messagingSenderId: '80235878542',
    projectId: 'yovoice-ec54a',
    authDomain: 'auth.yovoice.app',
    storageBucket: 'yovoice-ec54a.firebasestorage.app',
    measurementId: 'G-N66FNT890Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_gsL0-6hmaTjG_Gd2dcxRxWKjBTO1QhQ',
    appId: '1:80235878542:android:5734f129660d29da1351df',
    messagingSenderId: '80235878542',
    projectId: 'yovoice-ec54a',
    storageBucket: 'yovoice-ec54a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZFVCb39HuAAbQ49vDkPVC77r1r2zvRKc',
    appId: '1:80235878542:ios:6e9b8f6cff5ec88f1351df',
    messagingSenderId: '80235878542',
    projectId: 'yovoice-ec54a',
    storageBucket: 'yovoice-ec54a.firebasestorage.app',
    iosBundleId: 'com.example.yoVoice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZFVCb39HuAAbQ49vDkPVC77r1r2zvRKc',
    appId: '1:80235878542:ios:6e9b8f6cff5ec88f1351df',
    messagingSenderId: '80235878542',
    projectId: 'yovoice-ec54a',
    storageBucket: 'yovoice-ec54a.firebasestorage.app',
    iosBundleId: 'com.example.yoVoice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-tDFTRzkrKthxTXsskFM8tBwI4au9xHI',
    appId: '1:80235878542:web:81add24ce1e173381351df',
    messagingSenderId: '80235878542',
    projectId: 'yovoice-ec54a',
    authDomain: 'auth.yovoice.app',
    storageBucket: 'yovoice-ec54a.firebasestorage.app',
    measurementId: 'G-BM7DLKGNHV',
  );
}
