/// The emoji vocabulary offered by [YoEmojiPicker].
///
/// ## Why this ships as data instead of a package
///
/// Every Flutter emoji-picker package either bundles its own font, its own
/// asset blob, or a transitive plugin. YO Voice renders emoji with the
/// platform font, so the only thing actually missing was the vocabulary and
/// its search keywords — a plain Dart list, tree-shaken like the translation
/// catalogs, with no new dependency and no new resolution.
///
/// ## Platform support boundary
///
/// The entries below are bounded to **Unicode Emoji 5.0 (2017)** and earlier.
/// That is deliberate and it is the binding constraint, not a rough guess:
///
/// * iOS 15 ships Emoji 13.1 (14.0 from 15.4), so it covers everything here.
/// * Android 8.0 — the oldest release YO Voice supports — ships Emoji 5.0.
///
/// Android 8.0 is therefore the ceiling. Anything newer (🥰 🥺 🥳 🧊 🧁 from
/// Emoji 11, 🦩 🪀 from Emoji 12, 🥲 from Emoji 13, 🫠 from Emoji 14) renders
/// as a tofu box on a device that never received a font update, so none of it
/// is listed. Raising the ceiling is a one-line comment change here once the
/// minimum supported Android version moves — the picker code itself is
/// version-agnostic.
///
/// Skin-tone modifiers and gender ZWJ variants are intentionally out of scope
/// for this pass: they multiply the grid by five to twelve and deserve their
/// own selector rather than being smuggled in as extra cells.
library;

import 'package:flutter/foundation.dart';

/// A single selectable emoji together with everything needed to find it.
///
/// [name] doubles as the accessibility label, so it is a human phrase rather
/// than a Unicode identifier.
@immutable
class YoEmoji {
  const YoEmoji(
    this.char,
    this.name,
    this.namePolish, [
    this.keywords = '',
    this.keywordsPolish = '',
  ]);

  /// The emoji itself, as it is inserted into the composer.
  final String char;

  /// English display name, also used as the semantic label.
  final String name;

  /// Polish display name, also used as the semantic label in Polish.
  final String namePolish;

  /// Space-separated English search terms beyond [name].
  final String keywords;

  /// Space-separated Polish search terms beyond [namePolish].
  final String keywordsPolish;

  @override
  bool operator ==(Object other) =>
      other is YoEmoji && other.char == char;

  @override
  int get hashCode => char.hashCode;
}

/// The nine standard Unicode emoji groups, in the order the strip shows them.
enum YoEmojiCategory {
  smileys,
  people,
  animals,
  food,
  activity,
  travel,
  objects,
  symbols,
  flags,
}

const _smileys = <YoEmoji>[
  YoEmoji('😀', 'grinning face', 'uśmiechnięta twarz', 'smile happy grin', 'uśmiech radość'),
  YoEmoji('😃', 'grinning face with big eyes', 'roześmiana twarz', 'smile happy joy', 'uśmiech radość wesoło'),
  YoEmoji('😄', 'grinning face with smiling eyes', 'uśmiech z przymrużonymi oczami', 'smile happy laugh', 'uśmiech śmiech'),
  YoEmoji('😁', 'beaming face with smiling eyes', 'szeroki uśmiech', 'grin smile teeth', 'uśmiech zęby'),
  YoEmoji('😆', 'grinning squinting face', 'śmiech do rozpuku', 'laugh haha lol', 'śmiech hehe'),
  YoEmoji('😅', 'grinning face with sweat', 'uśmiech z kroplą potu', 'laugh sweat relief', 'śmiech pot ulga'),
  YoEmoji('🤣', 'rolling on the floor laughing', 'turlanie się ze śmiechu', 'rofl laugh lol', 'śmiech rozpuk lol'),
  YoEmoji('😂', 'face with tears of joy', 'łzy ze śmiechu', 'laugh cry lol funny', 'śmiech płacz łzy'),
  YoEmoji('🙂', 'slightly smiling face', 'lekko uśmiechnięta twarz', 'smile', 'uśmiech'),
  YoEmoji('🙃', 'upside-down face', 'twarz do góry nogami', 'silly irony sarcasm', 'ironia żart'),
  YoEmoji('😉', 'winking face', 'mrugająca twarz', 'wink flirt', 'mrugnięcie flirt'),
  YoEmoji('😊', 'smiling face with smiling eyes', 'rozpromieniona twarz', 'smile blush happy', 'uśmiech rumieniec'),
  YoEmoji('😇', 'smiling face with halo', 'twarz z aureolą', 'angel innocent', 'anioł niewinność'),
  YoEmoji('😍', 'smiling face with heart-eyes', 'serduszka w oczach', 'love crush heart', 'miłość zakochanie serce'),
  YoEmoji('😘', 'face blowing a kiss', 'całus', 'kiss love', 'buziak pocałunek miłość'),
  YoEmoji('😗', 'kissing face', 'buziak', 'kiss', 'pocałunek'),
  YoEmoji('😚', 'kissing face with closed eyes', 'całus z zamkniętymi oczami', 'kiss', 'pocałunek'),
  YoEmoji('😙', 'kissing face with smiling eyes', 'całus z uśmiechem', 'kiss smile', 'pocałunek uśmiech'),
  YoEmoji('😋', 'face savoring food', 'oblizująca się twarz', 'yum tasty delicious', 'mniam pyszne smaczne'),
  YoEmoji('😛', 'face with tongue', 'język', 'tongue silly', 'język żart'),
  YoEmoji('😜', 'winking face with tongue', 'mrugnięcie z językiem', 'crazy silly joke', 'żart wygłup'),
  YoEmoji('🤪', 'zany face', 'zwariowana twarz', 'crazy goofy wild', 'szaleństwo wygłup'),
  YoEmoji('😝', 'squinting face with tongue', 'wywalony język', 'tongue prank', 'język psota'),
  YoEmoji('🤑', 'money-mouth face', 'twarz z dolarami', 'money rich cash', 'pieniądze bogactwo kasa'),
  YoEmoji('🤗', 'hugging face', 'przytulenie', 'hug care', 'uścisk przytulas'),
  YoEmoji('🤭', 'face with hand over mouth', 'dłoń na ustach', 'oops giggle secret', 'ups chichot'),
  YoEmoji('🤫', 'shushing face', 'cisza', 'quiet secret shush', 'cicho sekret'),
  YoEmoji('🤔', 'thinking face', 'zamyślona twarz', 'think hmm wonder', 'myślenie zastanowienie hmm'),
  YoEmoji('🤐', 'zipper-mouth face', 'zamek na ustach', 'silence secret', 'milczenie sekret'),
  YoEmoji('🤨', 'face with raised eyebrow', 'uniesiona brew', 'suspicious doubt', 'podejrzliwość wątpliwość'),
  YoEmoji('😐', 'neutral face', 'neutralna twarz', 'meh blank', 'obojętność'),
  YoEmoji('😑', 'expressionless face', 'twarz bez wyrazu', 'blank annoyed', 'bez wyrazu znudzenie'),
  YoEmoji('😶', 'face without mouth', 'twarz bez ust', 'speechless silent', 'bez słów milczenie'),
  YoEmoji('😏', 'smirking face', 'uśmieszek', 'smug flirt', 'ironia zadowolenie'),
  YoEmoji('😒', 'unamused face', 'nieprzekonana twarz', 'meh unimpressed', 'znudzenie niezadowolenie'),
  YoEmoji('🙄', 'face with rolling eyes', 'przewracanie oczami', 'eyeroll annoyed', 'irytacja'),
  YoEmoji('😬', 'grimacing face', 'grymas', 'awkward cringe', 'zażenowanie niezręcznie'),
  YoEmoji('🤥', 'lying face', 'kłamiąca twarz', 'lie pinocchio', 'kłamstwo'),
  YoEmoji('😌', 'relieved face', 'ulga', 'calm relief', 'spokój ulga'),
  YoEmoji('😔', 'pensive face', 'zamyślony smutek', 'sad down', 'smutek przygnębienie'),
  YoEmoji('😪', 'sleepy face', 'senna twarz', 'tired sleep', 'senność zmęczenie'),
  YoEmoji('🤤', 'drooling face', 'ślinka', 'drool want', 'ślinka ochota'),
  YoEmoji('😴', 'sleeping face', 'śpiąca twarz', 'sleep zzz tired', 'sen spanie zmęczenie'),
  YoEmoji('😷', 'face with medical mask', 'twarz w maseczce', 'sick mask ill', 'choroba maseczka'),
  YoEmoji('🤒', 'face with thermometer', 'twarz z termometrem', 'sick fever ill', 'gorączka choroba'),
  YoEmoji('🤕', 'face with head-bandage', 'zabandażowana głowa', 'hurt injury', 'uraz ból'),
  YoEmoji('🤢', 'nauseated face', 'mdłości', 'sick gross disgust', 'obrzydzenie mdłości'),
  YoEmoji('🤮', 'face vomiting', 'wymioty', 'sick gross vomit', 'wymioty obrzydzenie'),
  YoEmoji('🤧', 'sneezing face', 'kichnięcie', 'sneeze cold sick', 'kichanie przeziębienie'),
  YoEmoji('🤠', 'cowboy hat face', 'kowboj', 'cowboy hat', 'kapelusz western'),
  YoEmoji('🤡', 'clown face', 'klaun', 'clown joke', 'błazen żart'),
  YoEmoji('🤓', 'nerd face', 'kujon', 'nerd geek glasses', 'okulary geek'),
  YoEmoji('🧐', 'face with monocle', 'monokl', 'inspect curious', 'badanie ciekawość'),
  YoEmoji('😎', 'smiling face with sunglasses', 'twarz w okularach', 'cool sunglasses', 'luz okulary'),
  YoEmoji('🤩', 'star-struck', 'gwiazdki w oczach', 'wow amazed star', 'zachwyt wow gwiazdy'),
  YoEmoji('😕', 'confused face', 'zdezorientowana twarz', 'confused unsure', 'zmieszanie'),
  YoEmoji('😟', 'worried face', 'zmartwiona twarz', 'worry concern', 'zmartwienie troska'),
  YoEmoji('🙁', 'slightly frowning face', 'lekko smutna twarz', 'sad', 'smutek'),
  YoEmoji('☹️', 'frowning face', 'smutna twarz', 'sad frown', 'smutek'),
  YoEmoji('😮', 'face with open mouth', 'otwarte usta', 'wow surprise shock', 'zaskoczenie wow'),
  YoEmoji('😯', 'hushed face', 'zaskoczenie', 'surprise quiet', 'zdziwienie'),
  YoEmoji('😲', 'astonished face', 'zdumienie', 'shock amazed', 'szok zdumienie'),
  YoEmoji('😳', 'flushed face', 'zawstydzona twarz', 'blush embarrassed', 'rumieniec wstyd'),
  YoEmoji('🤯', 'exploding head', 'eksplodująca głowa', 'mind blown shock', 'szok wybuch'),
  YoEmoji('😦', 'frowning face with open mouth', 'niezadowolenie', 'shock sad', 'zaskoczenie smutek'),
  YoEmoji('😧', 'anguished face', 'udręka', 'anguish pain', 'udręka ból'),
  YoEmoji('😨', 'fearful face', 'przestrach', 'fear scared', 'strach'),
  YoEmoji('😰', 'anxious face with sweat', 'lęk i pot', 'anxious nervous', 'lęk nerwy'),
  YoEmoji('😥', 'sad but relieved face', 'smutna ulga', 'sad relief', 'smutek ulga'),
  YoEmoji('😢', 'crying face', 'płacz', 'cry sad tear', 'płacz smutek łza'),
  YoEmoji('😭', 'loudly crying face', 'głośny płacz', 'sob cry sad', 'szloch płacz'),
  YoEmoji('😱', 'face screaming in fear', 'krzyk ze strachu', 'scream scared shock', 'krzyk strach'),
  YoEmoji('😖', 'confounded face', 'zmieszanie', 'confused frustrated', 'frustracja'),
  YoEmoji('😣', 'persevering face', 'wytrwałość', 'struggle', 'wysiłek'),
  YoEmoji('😞', 'disappointed face', 'rozczarowanie', 'sad let down', 'zawód smutek'),
  YoEmoji('😓', 'downcast face with sweat', 'przygnębienie', 'sad sweat', 'przygnębienie pot'),
  YoEmoji('😩', 'weary face', 'zmęczona twarz', 'tired weary', 'zmęczenie'),
  YoEmoji('😫', 'tired face', 'wyczerpana twarz', 'exhausted tired', 'wyczerpanie'),
  YoEmoji('😤', 'face with steam from nose', 'złość i para', 'angry proud steam', 'złość duma'),
  YoEmoji('😡', 'pouting face', 'wściekła twarz', 'angry mad rage', 'wściekłość gniew'),
  YoEmoji('😠', 'angry face', 'zła twarz', 'angry mad', 'złość gniew'),
  YoEmoji('🤬', 'face with symbols on mouth', 'przekleństwa', 'swearing angry curse', 'przekleństwa złość'),
  YoEmoji('😈', 'smiling face with horns', 'diabełek', 'devil mischief', 'diabeł psota'),
  YoEmoji('👿', 'angry face with horns', 'diabeł', 'devil angry', 'diabeł złość'),
  YoEmoji('💀', 'skull', 'czaszka', 'dead skull', 'śmierć trup'),
  YoEmoji('☠️', 'skull and crossbones', 'trupia czaszka', 'danger poison dead', 'niebezpieczeństwo trucizna'),
  YoEmoji('💩', 'pile of poo', 'kupka', 'poop funny', 'kupa żart'),
  YoEmoji('👻', 'ghost', 'duch', 'ghost halloween boo', 'duch halloween'),
  YoEmoji('👽', 'alien', 'kosmita', 'alien ufo space', 'ufo kosmos'),
  YoEmoji('🤖', 'robot', 'robot', 'robot bot ai', 'robot bot'),
  YoEmoji('😺', 'grinning cat', 'uśmiechnięty kot', 'cat smile', 'kot uśmiech'),
  YoEmoji('😹', 'cat with tears of joy', 'kot ze łzami śmiechu', 'cat laugh', 'kot śmiech'),
  YoEmoji('😻', 'smiling cat with heart-eyes', 'zakochany kot', 'cat love', 'kot miłość'),
  YoEmoji('😼', 'cat with wry smile', 'kot z uśmieszkiem', 'cat smug', 'kot ironia'),
  YoEmoji('🙀', 'weary cat', 'przestraszony kot', 'cat shock', 'kot szok'),
  YoEmoji('😿', 'crying cat', 'płaczący kot', 'cat sad cry', 'kot płacz'),
  YoEmoji('😾', 'pouting cat', 'naburmuszony kot', 'cat angry', 'kot złość'),
  YoEmoji('🙈', 'see-no-evil monkey', 'małpa zasłania oczy', 'monkey shy hide', 'małpa wstyd'),
  YoEmoji('🙉', 'hear-no-evil monkey', 'małpa zasłania uszy', 'monkey deaf', 'małpa uszy'),
  YoEmoji('🙊', 'speak-no-evil monkey', 'małpa zasłania usta', 'monkey quiet', 'małpa cisza'),
  YoEmoji('💋', 'kiss mark', 'ślad pocałunku', 'kiss lips love', 'pocałunek usta'),
  YoEmoji('💌', 'love letter', 'list miłosny', 'love letter', 'miłość list'),
  YoEmoji('💘', 'heart with arrow', 'serce ze strzałą', 'love cupid', 'miłość amor'),
  YoEmoji('💝', 'heart with ribbon', 'serce z kokardą', 'love gift', 'miłość prezent'),
  YoEmoji('💖', 'sparkling heart', 'migoczące serce', 'love sparkle', 'miłość blask'),
  YoEmoji('💗', 'growing heart', 'rosnące serce', 'love', 'miłość'),
  YoEmoji('💓', 'beating heart', 'bijące serce', 'love heartbeat', 'miłość bicie'),
  YoEmoji('💞', 'revolving hearts', 'wirujące serca', 'love', 'miłość'),
  YoEmoji('💕', 'two hearts', 'dwa serca', 'love', 'miłość'),
  YoEmoji('💔', 'broken heart', 'złamane serce', 'sad breakup', 'smutek rozstanie'),
  YoEmoji('❤️', 'red heart', 'czerwone serce', 'love like heart', 'miłość serce lubię'),
  YoEmoji('🧡', 'orange heart', 'pomarańczowe serce', 'love', 'miłość'),
  YoEmoji('💛', 'yellow heart', 'żółte serce', 'love friendship', 'miłość przyjaźń'),
  YoEmoji('💚', 'green heart', 'zielone serce', 'love', 'miłość'),
  YoEmoji('💙', 'blue heart', 'niebieskie serce', 'love', 'miłość'),
  YoEmoji('💜', 'purple heart', 'fioletowe serce', 'love', 'miłość'),
  YoEmoji('🖤', 'black heart', 'czarne serce', 'love dark', 'miłość mrok'),
  YoEmoji('💯', 'hundred points', 'setka', 'perfect score hundred', 'sto punktów idealnie'),
  YoEmoji('💢', 'anger symbol', 'symbol złości', 'angry', 'złość'),
  YoEmoji('💥', 'collision', 'wybuch', 'boom explosion', 'bum eksplozja'),
  YoEmoji('💫', 'dizzy', 'gwiazdki', 'stars dizzy', 'gwiazdy zawroty'),
  YoEmoji('💦', 'sweat droplets', 'krople potu', 'water sweat', 'woda pot'),
  YoEmoji('💨', 'dashing away', 'obłok pędu', 'fast wind run', 'szybko wiatr'),
  YoEmoji('🕳️', 'hole', 'dziura', 'hole', 'dziura'),
  YoEmoji('💣', 'bomb', 'bomba', 'bomb boom', 'bomba wybuch'),
  YoEmoji('💬', 'speech balloon', 'dymek', 'chat message talk', 'czat wiadomość rozmowa'),
  YoEmoji('💭', 'thought balloon', 'dymek myśli', 'think', 'myśl'),
  YoEmoji('💤', 'zzz', 'zzz', 'sleep tired', 'sen spanie'),
];

const _people = <YoEmoji>[
  YoEmoji('👋', 'waving hand', 'machająca dłoń', 'hello bye wave', 'cześć pa machanie'),
  YoEmoji('🤚', 'raised back of hand', 'wierzch dłoni', 'hand stop', 'dłoń stop'),
  YoEmoji('🖐️', 'hand with fingers splayed', 'rozłożone palce', 'hand five', 'dłoń pięć'),
  YoEmoji('✋', 'raised hand', 'uniesiona dłoń', 'stop high five', 'stop piątka'),
  YoEmoji('🖖', 'vulcan salute', 'pozdrowienie Wolkanina', 'spock star trek', 'spock'),
  YoEmoji('👌', 'OK hand', 'gest OK', 'ok perfect good', 'ok dobrze świetnie'),
  YoEmoji('✌️', 'victory hand', 'znak zwycięstwa', 'peace victory two', 'pokój zwycięstwo'),
  YoEmoji('🤞', 'crossed fingers', 'skrzyżowane palce', 'luck hope', 'szczęście nadzieja kciuki'),
  YoEmoji('🤟', 'love-you gesture', 'gest kocham cię', 'love ily', 'miłość kocham'),
  YoEmoji('🤘', 'sign of the horns', 'rogi', 'rock metal', 'rock metal'),
  YoEmoji('🤙', 'call me hand', 'zadzwoń do mnie', 'call shaka', 'zadzwoń'),
  YoEmoji('👈', 'backhand index pointing left', 'palec w lewo', 'point left', 'wskazuje lewo'),
  YoEmoji('👉', 'backhand index pointing right', 'palec w prawo', 'point right', 'wskazuje prawo'),
  YoEmoji('👆', 'backhand index pointing up', 'palec w górę', 'point up', 'wskazuje góra'),
  YoEmoji('👇', 'backhand index pointing down', 'palec w dół', 'point down', 'wskazuje dół'),
  YoEmoji('☝️', 'index pointing up', 'palec wskazujący w górę', 'point one', 'wskazuje jeden'),
  YoEmoji('👍', 'thumbs up', 'kciuk w górę', 'like yes good approve', 'lubię tak dobrze zgoda'),
  YoEmoji('👎', 'thumbs down', 'kciuk w dół', 'dislike no bad', 'nie lubię źle'),
  YoEmoji('✊', 'raised fist', 'uniesiona pięść', 'fist power', 'pięść siła'),
  YoEmoji('👊', 'oncoming fist', 'pięść', 'punch bump', 'żółwik cios'),
  YoEmoji('🤛', 'left-facing fist', 'pięść w lewo', 'fist bump', 'żółwik'),
  YoEmoji('🤜', 'right-facing fist', 'pięść w prawo', 'fist bump', 'żółwik'),
  YoEmoji('👏', 'clapping hands', 'brawa', 'clap applause bravo', 'oklaski brawo'),
  YoEmoji('🙌', 'raising hands', 'uniesione ręce', 'celebrate hooray praise', 'radość hurra'),
  YoEmoji('👐', 'open hands', 'otwarte dłonie', 'hug open', 'otwarte przytulenie'),
  YoEmoji('🤲', 'palms up together', 'dłonie w górę', 'pray please', 'modlitwa prośba'),
  YoEmoji('🤝', 'handshake', 'uścisk dłoni', 'deal agree meet', 'umowa zgoda powitanie'),
  YoEmoji('🙏', 'folded hands', 'złożone dłonie', 'thanks pray please', 'dzięki modlitwa proszę'),
  YoEmoji('✍️', 'writing hand', 'pisząca dłoń', 'write note', 'pisanie notatka'),
  YoEmoji('💅', 'nail polish', 'lakier do paznokci', 'nails manicure', 'paznokcie manicure'),
  YoEmoji('🤳', 'selfie', 'selfie', 'selfie photo', 'selfie zdjęcie'),
  YoEmoji('💪', 'flexed biceps', 'biceps', 'strong muscle gym', 'siła mięśnie siłownia'),
  YoEmoji('🧠', 'brain', 'mózg', 'smart think', 'myślenie inteligencja'),
  YoEmoji('👀', 'eyes', 'oczy', 'look see watch', 'patrz zobacz'),
  YoEmoji('👁️', 'eye', 'oko', 'look see', 'patrzeć'),
  YoEmoji('👅', 'tongue', 'język', 'tongue taste', 'język smak'),
  YoEmoji('👄', 'mouth', 'usta', 'lips kiss', 'usta pocałunek'),
  YoEmoji('👶', 'baby', 'niemowlę', 'baby child', 'dziecko bobas'),
  YoEmoji('🧒', 'child', 'dziecko', 'kid child', 'dziecko'),
  YoEmoji('👦', 'boy', 'chłopiec', 'boy kid', 'chłopak dziecko'),
  YoEmoji('👧', 'girl', 'dziewczynka', 'girl kid', 'dziewczyna dziecko'),
  YoEmoji('🧑', 'person', 'osoba', 'person adult', 'osoba dorosły'),
  YoEmoji('👨', 'man', 'mężczyzna', 'man guy', 'facet mężczyzna'),
  YoEmoji('👩', 'woman', 'kobieta', 'woman lady', 'kobieta'),
  YoEmoji('🧓', 'older person', 'starsza osoba', 'old senior', 'senior starszy'),
  YoEmoji('👴', 'old man', 'starszy mężczyzna', 'grandpa old', 'dziadek'),
  YoEmoji('👵', 'old woman', 'starsza kobieta', 'grandma old', 'babcia'),
  YoEmoji('🧔', 'person with beard', 'osoba z brodą', 'beard', 'broda'),
  YoEmoji('👮', 'police officer', 'policjant', 'police cop', 'policja'),
  YoEmoji('👷', 'construction worker', 'robotnik budowlany', 'worker build', 'budowa robotnik'),
  YoEmoji('💂', 'guard', 'gwardzista', 'guard royal', 'gwardia'),
  YoEmoji('🕵️', 'detective', 'detektyw', 'spy detective', 'szpieg detektyw'),
  YoEmoji('🤴', 'prince', 'książę', 'prince royal', 'książę'),
  YoEmoji('👸', 'princess', 'księżniczka', 'princess royal', 'księżniczka'),
  YoEmoji('👳', 'person wearing turban', 'osoba w turbanie', 'turban', 'turban'),
  YoEmoji('🧕', 'woman with headscarf', 'kobieta w chuście', 'hijab scarf', 'chusta hidżab'),
  YoEmoji('🤵', 'person in tuxedo', 'osoba w smokingu', 'tuxedo wedding', 'smoking ślub'),
  YoEmoji('👰', 'person with veil', 'osoba w welonie', 'bride wedding', 'panna młoda ślub'),
  YoEmoji('🤰', 'pregnant woman', 'kobieta w ciąży', 'pregnant baby', 'ciąża'),
  YoEmoji('🤱', 'breast-feeding', 'karmienie piersią', 'baby feed', 'karmienie dziecko'),
  YoEmoji('👼', 'baby angel', 'aniołek', 'angel', 'anioł'),
  YoEmoji('🎅', 'Santa Claus', 'Mikołaj', 'christmas santa', 'święta mikołaj'),
  YoEmoji('🤶', 'Mrs. Claus', 'Pani Mikołajowa', 'christmas', 'święta'),
  YoEmoji('🧙', 'mage', 'mag', 'wizard magic', 'czarodziej magia'),
  YoEmoji('🧚', 'fairy', 'wróżka', 'fairy magic', 'wróżka magia'),
  YoEmoji('🧛', 'vampire', 'wampir', 'vampire halloween', 'wampir halloween'),
  YoEmoji('🧜', 'merperson', 'syrena', 'mermaid', 'syrena'),
  YoEmoji('🧝', 'elf', 'elf', 'elf fantasy', 'elf fantasy'),
  YoEmoji('🧞', 'genie', 'dżin', 'genie wish', 'dżin życzenie'),
  YoEmoji('🧟', 'zombie', 'zombie', 'zombie halloween', 'zombie halloween'),
  YoEmoji('💆', 'person getting massage', 'masaż', 'massage spa relax', 'masaż relaks'),
  YoEmoji('💇', 'person getting haircut', 'fryzjer', 'haircut salon', 'fryzura salon'),
  YoEmoji('🚶', 'person walking', 'idąca osoba', 'walk', 'spacer chodzenie'),
  YoEmoji('🏃', 'person running', 'biegnąca osoba', 'run hurry', 'bieg pośpiech'),
  YoEmoji('💃', 'woman dancing', 'tańcząca kobieta', 'dance party', 'taniec impreza'),
  YoEmoji('🕺', 'man dancing', 'tańczący mężczyzna', 'dance party', 'taniec impreza'),
  YoEmoji('👯', 'people with bunny ears', 'króliczki', 'party dance', 'impreza taniec'),
  YoEmoji('🧖', 'person in steamy room', 'sauna', 'sauna spa', 'sauna spa'),
  YoEmoji('🧗', 'person climbing', 'wspinaczka', 'climb', 'wspinaczka'),
  YoEmoji('🧘', 'person in lotus position', 'medytacja', 'yoga meditate calm', 'joga medytacja spokój'),
  YoEmoji('🛀', 'person taking bath', 'kąpiel', 'bath relax', 'kąpiel relaks'),
  YoEmoji('🛌', 'person in bed', 'osoba w łóżku', 'sleep bed', 'sen łóżko'),
  YoEmoji('👤', 'bust in silhouette', 'sylwetka', 'user person', 'użytkownik osoba'),
  YoEmoji('👥', 'busts in silhouette', 'sylwetki', 'users group people', 'użytkownicy grupa'),
  YoEmoji('👣', 'footprints', 'ślady stóp', 'steps feet', 'kroki stopy'),
];

const _animals = <YoEmoji>[
  YoEmoji('🐵', 'monkey face', 'pysk małpy', 'monkey', 'małpa'),
  YoEmoji('🐒', 'monkey', 'małpa', 'monkey', 'małpa'),
  YoEmoji('🦍', 'gorilla', 'goryl', 'gorilla ape', 'goryl małpa'),
  YoEmoji('🐶', 'dog face', 'pysk psa', 'dog puppy', 'pies piesek'),
  YoEmoji('🐕', 'dog', 'pies', 'dog', 'pies'),
  YoEmoji('🐩', 'poodle', 'pudel', 'dog poodle', 'pies pudel'),
  YoEmoji('🐺', 'wolf', 'wilk', 'wolf', 'wilk'),
  YoEmoji('🦊', 'fox', 'lis', 'fox', 'lis'),
  YoEmoji('🐱', 'cat face', 'pysk kota', 'cat kitten', 'kot kotek'),
  YoEmoji('🐈', 'cat', 'kot', 'cat', 'kot'),
  YoEmoji('🦁', 'lion', 'lew', 'lion', 'lew'),
  YoEmoji('🐯', 'tiger face', 'pysk tygrysa', 'tiger', 'tygrys'),
  YoEmoji('🐅', 'tiger', 'tygrys', 'tiger', 'tygrys'),
  YoEmoji('🐆', 'leopard', 'lampart', 'leopard', 'lampart'),
  YoEmoji('🐴', 'horse face', 'pysk konia', 'horse', 'koń'),
  YoEmoji('🐎', 'horse', 'koń', 'horse', 'koń'),
  YoEmoji('🦄', 'unicorn', 'jednorożec', 'unicorn magic', 'jednorożec magia'),
  YoEmoji('🦓', 'zebra', 'zebra', 'zebra', 'zebra'),
  YoEmoji('🦌', 'deer', 'jeleń', 'deer', 'jeleń sarna'),
  YoEmoji('🐮', 'cow face', 'pysk krowy', 'cow', 'krowa'),
  YoEmoji('🐄', 'cow', 'krowa', 'cow', 'krowa'),
  YoEmoji('🐷', 'pig face', 'pysk świni', 'pig', 'świnia'),
  YoEmoji('🐗', 'boar', 'dzik', 'boar', 'dzik'),
  YoEmoji('🐑', 'ewe', 'owca', 'sheep', 'owca'),
  YoEmoji('🐐', 'goat', 'koza', 'goat', 'koza'),
  YoEmoji('🐪', 'camel', 'wielbłąd', 'camel desert', 'wielbłąd pustynia'),
  YoEmoji('🦒', 'giraffe', 'żyrafa', 'giraffe', 'żyrafa'),
  YoEmoji('🐘', 'elephant', 'słoń', 'elephant', 'słoń'),
  YoEmoji('🦏', 'rhinoceros', 'nosorożec', 'rhino', 'nosorożec'),
  YoEmoji('🐭', 'mouse face', 'pysk myszy', 'mouse', 'mysz'),
  YoEmoji('🐁', 'mouse', 'mysz', 'mouse', 'mysz'),
  YoEmoji('🐀', 'rat', 'szczur', 'rat', 'szczur'),
  YoEmoji('🐹', 'hamster', 'chomik', 'hamster', 'chomik'),
  YoEmoji('🐰', 'rabbit face', 'pysk królika', 'rabbit bunny', 'królik zajączek'),
  YoEmoji('🐇', 'rabbit', 'królik', 'rabbit bunny', 'królik'),
  YoEmoji('🐿️', 'chipmunk', 'wiewiórka', 'squirrel', 'wiewiórka'),
  YoEmoji('🦔', 'hedgehog', 'jeż', 'hedgehog', 'jeż'),
  YoEmoji('🦇', 'bat', 'nietoperz', 'bat', 'nietoperz'),
  YoEmoji('🐻', 'bear', 'niedźwiedź', 'bear', 'miś niedźwiedź'),
  YoEmoji('🐨', 'koala', 'koala', 'koala', 'koala'),
  YoEmoji('🐼', 'panda', 'panda', 'panda', 'panda'),
  YoEmoji('🐾', 'paw prints', 'ślady łap', 'paw pet', 'łapy zwierzę'),
  YoEmoji('🦃', 'turkey', 'indyk', 'turkey', 'indyk'),
  YoEmoji('🐔', 'chicken', 'kurczak', 'chicken hen', 'kura kurczak'),
  YoEmoji('🐓', 'rooster', 'kogut', 'rooster', 'kogut'),
  YoEmoji('🐣', 'hatching chick', 'wykluwający się pisklak', 'chick egg', 'pisklę jajko'),
  YoEmoji('🐤', 'baby chick', 'pisklę', 'chick', 'pisklę kurczaczek'),
  YoEmoji('🐦', 'bird', 'ptak', 'bird', 'ptak'),
  YoEmoji('🐧', 'penguin', 'pingwin', 'penguin', 'pingwin'),
  YoEmoji('🕊️', 'dove', 'gołąb', 'peace dove bird', 'pokój gołąb'),
  YoEmoji('🦅', 'eagle', 'orzeł', 'eagle bird', 'orzeł'),
  YoEmoji('🦆', 'duck', 'kaczka', 'duck', 'kaczka'),
  YoEmoji('🦉', 'owl', 'sowa', 'owl', 'sowa'),
  YoEmoji('🐸', 'frog', 'żaba', 'frog', 'żaba'),
  YoEmoji('🐊', 'crocodile', 'krokodyl', 'crocodile alligator', 'krokodyl'),
  YoEmoji('🐢', 'turtle', 'żółw', 'turtle slow', 'żółw wolno'),
  YoEmoji('🦎', 'lizard', 'jaszczurka', 'lizard', 'jaszczurka'),
  YoEmoji('🐍', 'snake', 'wąż', 'snake', 'wąż'),
  YoEmoji('🐲', 'dragon face', 'pysk smoka', 'dragon', 'smok'),
  YoEmoji('🐉', 'dragon', 'smok', 'dragon', 'smok'),
  YoEmoji('🦕', 'sauropod', 'zauropod', 'dinosaur', 'dinozaur'),
  YoEmoji('🦖', 'T-Rex', 'tyranozaur', 'dinosaur trex', 'dinozaur'),
  YoEmoji('🐳', 'spouting whale', 'wieloryb', 'whale sea', 'wieloryb morze'),
  YoEmoji('🐬', 'dolphin', 'delfin', 'dolphin sea', 'delfin morze'),
  YoEmoji('🐟', 'fish', 'ryba', 'fish', 'ryba'),
  YoEmoji('🐠', 'tropical fish', 'ryba tropikalna', 'fish reef', 'ryba rafa'),
  YoEmoji('🦈', 'shark', 'rekin', 'shark', 'rekin'),
  YoEmoji('🐙', 'octopus', 'ośmiornica', 'octopus', 'ośmiornica'),
  YoEmoji('🐚', 'spiral shell', 'muszla', 'shell beach', 'muszla plaża'),
  YoEmoji('🦀', 'crab', 'krab', 'crab', 'krab'),
  YoEmoji('🦐', 'shrimp', 'krewetka', 'shrimp', 'krewetka'),
  YoEmoji('🦑', 'squid', 'kalmar', 'squid', 'kalmar'),
  YoEmoji('🐌', 'snail', 'ślimak', 'snail slow', 'ślimak wolno'),
  YoEmoji('🦋', 'butterfly', 'motyl', 'butterfly', 'motyl'),
  YoEmoji('🐛', 'bug', 'robak', 'bug caterpillar', 'robak gąsienica'),
  YoEmoji('🐜', 'ant', 'mrówka', 'ant', 'mrówka'),
  YoEmoji('🐝', 'honeybee', 'pszczoła', 'bee honey', 'pszczoła miód'),
  YoEmoji('🐞', 'lady beetle', 'biedronka', 'ladybug luck', 'biedronka szczęście'),
  YoEmoji('🦗', 'cricket', 'świerszcz', 'cricket', 'świerszcz'),
  YoEmoji('🕷️', 'spider', 'pająk', 'spider', 'pająk'),
  YoEmoji('🕸️', 'spider web', 'pajęczyna', 'web halloween', 'pajęczyna halloween'),
  YoEmoji('🦂', 'scorpion', 'skorpion', 'scorpion', 'skorpion'),
  YoEmoji('💐', 'bouquet', 'bukiet', 'flowers gift', 'kwiaty prezent'),
  YoEmoji('🌸', 'cherry blossom', 'kwiat wiśni', 'flower spring sakura', 'kwiat wiosna'),
  YoEmoji('🏵️', 'rosette', 'rozeta', 'flower badge', 'kwiat odznaka'),
  YoEmoji('🌹', 'rose', 'róża', 'flower love rose', 'kwiat miłość róża'),
  YoEmoji('🥀', 'wilted flower', 'zwiędły kwiat', 'flower sad', 'kwiat smutek'),
  YoEmoji('🌺', 'hibiscus', 'hibiskus', 'flower tropical', 'kwiat tropiki'),
  YoEmoji('🌻', 'sunflower', 'słonecznik', 'flower sun', 'kwiat słońce'),
  YoEmoji('🌼', 'blossom', 'kwiatek', 'flower daisy', 'kwiat stokrotka'),
  YoEmoji('🌷', 'tulip', 'tulipan', 'flower tulip', 'kwiat tulipan'),
  YoEmoji('🌱', 'seedling', 'sadzonka', 'plant grow new', 'roślina wzrost'),
  YoEmoji('🌲', 'evergreen tree', 'drzewo iglaste', 'tree forest', 'drzewo las'),
  YoEmoji('🌳', 'deciduous tree', 'drzewo liściaste', 'tree forest', 'drzewo las'),
  YoEmoji('🌴', 'palm tree', 'palma', 'tree tropical beach', 'drzewo palma plaża'),
  YoEmoji('🌵', 'cactus', 'kaktus', 'cactus desert', 'kaktus pustynia'),
  YoEmoji('🌾', 'sheaf of rice', 'kłosy', 'grain harvest', 'zboże żniwa'),
  YoEmoji('🌿', 'herb', 'zioło', 'plant herb', 'roślina zioło'),
  YoEmoji('☘️', 'shamrock', 'koniczyna', 'clover luck', 'koniczyna szczęście'),
  YoEmoji('🍀', 'four leaf clover', 'czterolistna koniczyna', 'luck clover', 'szczęście koniczyna'),
  YoEmoji('🍁', 'maple leaf', 'liść klonu', 'leaf autumn', 'liść jesień'),
  YoEmoji('🍂', 'fallen leaf', 'opadły liść', 'leaf autumn', 'liść jesień'),
  YoEmoji('🍃', 'leaf fluttering in wind', 'liść na wietrze', 'leaf wind', 'liść wiatr'),
];

const _food = <YoEmoji>[
  YoEmoji('🍇', 'grapes', 'winogrona', 'fruit grapes', 'owoc winogrona'),
  YoEmoji('🍈', 'melon', 'melon', 'fruit melon', 'owoc melon'),
  YoEmoji('🍉', 'watermelon', 'arbuz', 'fruit summer', 'owoc lato arbuz'),
  YoEmoji('🍊', 'tangerine', 'mandarynka', 'fruit orange', 'owoc pomarańcza'),
  YoEmoji('🍋', 'lemon', 'cytryna', 'fruit sour', 'owoc kwaśny cytryna'),
  YoEmoji('🍌', 'banana', 'banan', 'fruit banana', 'owoc banan'),
  YoEmoji('🍍', 'pineapple', 'ananas', 'fruit tropical', 'owoc ananas'),
  YoEmoji('🥥', 'coconut', 'kokos', 'fruit tropical', 'owoc kokos'),
  YoEmoji('🥝', 'kiwi fruit', 'kiwi', 'fruit kiwi', 'owoc kiwi'),
  YoEmoji('🍅', 'tomato', 'pomidor', 'vegetable tomato', 'warzywo pomidor'),
  YoEmoji('🍆', 'eggplant', 'bakłażan', 'vegetable', 'warzywo bakłażan'),
  YoEmoji('🥑', 'avocado', 'awokado', 'fruit avocado', 'owoc awokado'),
  YoEmoji('🥦', 'broccoli', 'brokuł', 'vegetable', 'warzywo brokuł'),
  YoEmoji('🥒', 'cucumber', 'ogórek', 'vegetable pickle', 'warzywo ogórek'),
  YoEmoji('🌶️', 'hot pepper', 'ostra papryka', 'spicy chili hot', 'ostre papryka chili'),
  YoEmoji('🌽', 'ear of corn', 'kukurydza', 'corn', 'kukurydza'),
  YoEmoji('🥕', 'carrot', 'marchewka', 'vegetable carrot', 'warzywo marchewka'),
  YoEmoji('🥔', 'potato', 'ziemniak', 'vegetable potato', 'warzywo ziemniak'),
  YoEmoji('🍠', 'roasted sweet potato', 'pieczony batat', 'potato', 'batat'),
  YoEmoji('🥐', 'croissant', 'rogalik', 'bread breakfast', 'pieczywo śniadanie'),
  YoEmoji('🍞', 'bread', 'chleb', 'bread', 'chleb pieczywo'),
  YoEmoji('🥖', 'baguette bread', 'bagietka', 'bread french', 'pieczywo bagietka'),
  YoEmoji('🥨', 'pretzel', 'precel', 'bread pretzel', 'precel'),
  YoEmoji('🧀', 'cheese wedge', 'ser', 'cheese', 'ser'),
  YoEmoji('🥚', 'egg', 'jajko', 'egg', 'jajko'),
  YoEmoji('🍳', 'cooking', 'jajko sadzone', 'egg breakfast cook', 'jajko śniadanie gotowanie'),
  YoEmoji('🥓', 'bacon', 'bekon', 'bacon meat', 'bekon mięso'),
  YoEmoji('🥩', 'cut of meat', 'kawałek mięsa', 'meat steak', 'mięso stek'),
  YoEmoji('🍗', 'poultry leg', 'udko', 'chicken meat', 'kurczak mięso'),
  YoEmoji('🍖', 'meat on bone', 'mięso na kości', 'meat', 'mięso'),
  YoEmoji('🌭', 'hot dog', 'hot dog', 'hotdog fast food', 'hot dog'),
  YoEmoji('🍔', 'hamburger', 'hamburger', 'burger fast food', 'burger fast food'),
  YoEmoji('🍟', 'french fries', 'frytki', 'fries fast food', 'frytki'),
  YoEmoji('🍕', 'pizza', 'pizza', 'pizza food', 'pizza jedzenie'),
  YoEmoji('🥪', 'sandwich', 'kanapka', 'sandwich', 'kanapka'),
  YoEmoji('🥙', 'stuffed flatbread', 'kebab', 'kebab wrap', 'kebab'),
  YoEmoji('🌮', 'taco', 'taco', 'taco mexican', 'taco'),
  YoEmoji('🌯', 'burrito', 'burrito', 'burrito wrap', 'burrito'),
  YoEmoji('🥗', 'green salad', 'sałatka', 'salad healthy', 'sałatka zdrowo'),
  YoEmoji('🥘', 'shallow pan of food', 'patelnia', 'pan cook', 'patelnia gotowanie'),
  YoEmoji('🍝', 'spaghetti', 'spaghetti', 'pasta italian', 'makaron spaghetti'),
  YoEmoji('🍜', 'steaming bowl', 'zupa', 'noodles ramen soup', 'zupa makaron ramen'),
  YoEmoji('🍲', 'pot of food', 'gulasz', 'stew soup', 'gulasz zupa'),
  YoEmoji('🍣', 'sushi', 'sushi', 'sushi japanese', 'sushi'),
  YoEmoji('🍱', 'bento box', 'bento', 'bento lunch', 'bento lunch'),
  YoEmoji('🍛', 'curry rice', 'curry z ryżem', 'curry rice', 'curry ryż'),
  YoEmoji('🍚', 'cooked rice', 'ryż', 'rice', 'ryż'),
  YoEmoji('🍙', 'rice ball', 'kulka ryżowa', 'rice onigiri', 'ryż onigiri'),
  YoEmoji('🥟', 'dumpling', 'pierożek', 'dumpling pierogi', 'pieróg pierogi'),
  YoEmoji('🥠', 'fortune cookie', 'ciasteczko z wróżbą', 'cookie fortune', 'ciastko wróżba'),
  YoEmoji('🍤', 'fried shrimp', 'krewetka w cieście', 'shrimp fried', 'krewetka'),
  YoEmoji('🍧', 'shaved ice', 'lód kruszony', 'ice dessert', 'lód deser'),
  YoEmoji('🍨', 'ice cream', 'lody', 'ice cream dessert', 'lody deser'),
  YoEmoji('🍦', 'soft ice cream', 'lody z automatu', 'ice cream', 'lody'),
  YoEmoji('🥧', 'pie', 'tarta', 'pie dessert', 'tarta ciasto'),
  YoEmoji('🍰', 'shortcake', 'ciastko', 'cake dessert', 'ciasto deser'),
  YoEmoji('🎂', 'birthday cake', 'tort urodzinowy', 'birthday cake party', 'urodziny tort'),
  YoEmoji('🍮', 'custard', 'budyń', 'pudding dessert', 'budyń deser'),
  YoEmoji('🍭', 'lollipop', 'lizak', 'candy sweet', 'cukierek lizak'),
  YoEmoji('🍬', 'candy', 'cukierek', 'candy sweet', 'cukierek słodycze'),
  YoEmoji('🍫', 'chocolate bar', 'czekolada', 'chocolate sweet', 'czekolada słodycze'),
  YoEmoji('🍿', 'popcorn', 'popcorn', 'popcorn movie', 'popcorn kino'),
  YoEmoji('🍩', 'doughnut', 'pączek', 'donut sweet', 'pączek donut'),
  YoEmoji('🍪', 'cookie', 'ciastko', 'cookie sweet', 'ciastko herbatnik'),
  YoEmoji('🥛', 'glass of milk', 'szklanka mleka', 'milk drink', 'mleko napój'),
  YoEmoji('☕', 'hot beverage', 'gorący napój', 'coffee tea drink', 'kawa herbata napój'),
  YoEmoji('🍵', 'teacup without handle', 'herbata', 'tea drink', 'herbata napój'),
  YoEmoji('🍶', 'sake', 'sake', 'sake drink', 'sake napój'),
  YoEmoji('🍾', 'bottle with popping cork', 'szampan', 'champagne celebrate', 'szampan świętowanie'),
  YoEmoji('🍷', 'wine glass', 'kieliszek wina', 'wine drink', 'wino napój'),
  YoEmoji('🍸', 'cocktail glass', 'koktajl', 'cocktail drink', 'koktajl drink'),
  YoEmoji('🍹', 'tropical drink', 'drink tropikalny', 'cocktail drink', 'drink koktajl'),
  YoEmoji('🍺', 'beer mug', 'kufel piwa', 'beer drink', 'piwo napój'),
  YoEmoji('🍻', 'clinking beer mugs', 'toast piwem', 'beer cheers', 'piwo toast'),
  YoEmoji('🥂', 'clinking glasses', 'toast', 'cheers celebrate', 'toast świętowanie'),
  YoEmoji('🥃', 'tumbler glass', 'szklanka whisky', 'whisky drink', 'whisky napój'),
  YoEmoji('🥤', 'cup with straw', 'napój ze słomką', 'soda drink', 'napój soda'),
  YoEmoji('🍽️', 'fork and knife with plate', 'talerz ze sztućcami', 'dinner eat', 'obiad jedzenie'),
  YoEmoji('🍴', 'fork and knife', 'sztućce', 'eat cutlery', 'jedzenie sztućce'),
  YoEmoji('🥄', 'spoon', 'łyżka', 'spoon', 'łyżka'),
  YoEmoji('🥢', 'chopsticks', 'pałeczki', 'chopsticks', 'pałeczki'),
];

const _activity = <YoEmoji>[
  YoEmoji('⚽', 'soccer ball', 'piłka nożna', 'football soccer sport', 'piłka nożna sport'),
  YoEmoji('🏀', 'basketball', 'koszykówka', 'basketball sport', 'koszykówka sport'),
  YoEmoji('🏈', 'american football', 'futbol amerykański', 'football sport', 'futbol sport'),
  YoEmoji('⚾', 'baseball', 'baseball', 'baseball sport', 'baseball sport'),
  YoEmoji('🎾', 'tennis', 'tenis', 'tennis sport', 'tenis sport'),
  YoEmoji('🏐', 'volleyball', 'siatkówka', 'volleyball sport', 'siatkówka sport'),
  YoEmoji('🏉', 'rugby football', 'rugby', 'rugby sport', 'rugby sport'),
  YoEmoji('🎱', 'pool 8 ball', 'bilard', 'billiards pool', 'bilard'),
  YoEmoji('🏓', 'ping pong', 'ping-pong', 'table tennis', 'tenis stołowy'),
  YoEmoji('🏸', 'badminton', 'badminton', 'badminton sport', 'badminton sport'),
  YoEmoji('🥅', 'goal net', 'bramka', 'goal sport', 'bramka sport'),
  YoEmoji('🏒', 'ice hockey', 'hokej na lodzie', 'hockey sport', 'hokej sport'),
  YoEmoji('🏑', 'field hockey', 'hokej na trawie', 'hockey sport', 'hokej sport'),
  YoEmoji('🏏', 'cricket game', 'krykiet', 'cricket sport', 'krykiet sport'),
  YoEmoji('⛳', 'flag in hole', 'golf', 'golf sport', 'golf sport'),
  YoEmoji('🏹', 'bow and arrow', 'łuk i strzała', 'archery', 'łucznictwo'),
  YoEmoji('🎣', 'fishing pole', 'wędka', 'fishing', 'wędkarstwo'),
  YoEmoji('🥊', 'boxing glove', 'rękawica bokserska', 'boxing sport', 'boks sport'),
  YoEmoji('🥋', 'martial arts uniform', 'kimono', 'karate judo', 'karate judo'),
  YoEmoji('⛸️', 'ice skate', 'łyżwa', 'skating', 'łyżwiarstwo'),
  YoEmoji('🎿', 'skis', 'narty', 'ski winter', 'narty zima'),
  YoEmoji('⛷️', 'skier', 'narciarz', 'ski winter', 'narty zima'),
  YoEmoji('🏂', 'snowboarder', 'snowboardzista', 'snowboard winter', 'snowboard zima'),
  YoEmoji('🏋️', 'person lifting weights', 'podnoszenie ciężarów', 'gym workout', 'siłownia trening'),
  YoEmoji('🤼', 'people wrestling', 'zapasy', 'wrestling sport', 'zapasy sport'),
  YoEmoji('🤸', 'person cartwheeling', 'gwiazda', 'gymnastics', 'gimnastyka'),
  YoEmoji('🤺', 'person fencing', 'szermierka', 'fencing sport', 'szermierka'),
  YoEmoji('🏌️', 'person golfing', 'golfista', 'golf sport', 'golf'),
  YoEmoji('🏇', 'horse racing', 'wyścig konny', 'racing horse', 'wyścig koń'),
  YoEmoji('🏄', 'person surfing', 'surfing', 'surf beach', 'surfing plaża'),
  YoEmoji('🏊', 'person swimming', 'pływanie', 'swim pool', 'pływanie basen'),
  YoEmoji('🚣', 'person rowing boat', 'wioślarstwo', 'rowing boat', 'wioślarstwo łódka'),
  YoEmoji('🚵', 'person mountain biking', 'kolarstwo górskie', 'bike mtb', 'rower góry'),
  YoEmoji('🚴', 'person biking', 'rowerzysta', 'bike cycling', 'rower kolarstwo'),
  YoEmoji('🏆', 'trophy', 'puchar', 'win trophy award', 'wygrana puchar nagroda'),
  YoEmoji('🥇', '1st place medal', 'złoty medal', 'gold win first', 'złoto wygrana pierwsze'),
  YoEmoji('🥈', '2nd place medal', 'srebrny medal', 'silver second', 'srebro drugie'),
  YoEmoji('🥉', '3rd place medal', 'brązowy medal', 'bronze third', 'brąz trzecie'),
  YoEmoji('🏅', 'sports medal', 'medal', 'medal award', 'medal nagroda'),
  YoEmoji('🎖️', 'military medal', 'medal wojskowy', 'medal honour', 'medal odznaczenie'),
  YoEmoji('🎗️', 'reminder ribbon', 'wstążka', 'ribbon awareness', 'wstążka'),
  YoEmoji('🎫', 'ticket', 'bilet', 'ticket event', 'bilet wydarzenie'),
  YoEmoji('🎟️', 'admission tickets', 'bilety wstępu', 'ticket event', 'bilety wydarzenie'),
  YoEmoji('🎪', 'circus tent', 'cyrk', 'circus', 'cyrk'),
  YoEmoji('🤹', 'person juggling', 'żonglerka', 'juggle circus', 'żonglowanie cyrk'),
  YoEmoji('🎭', 'performing arts', 'teatr', 'theatre drama', 'teatr dramat'),
  YoEmoji('🎨', 'artist palette', 'paleta malarska', 'art paint', 'sztuka malowanie'),
  YoEmoji('🎬', 'clapper board', 'klaps filmowy', 'movie film action', 'film kino akcja'),
  YoEmoji('🎤', 'microphone', 'mikrofon', 'mic sing voice karaoke', 'mikrofon śpiew głos karaoke'),
  YoEmoji('🎧', 'headphone', 'słuchawki', 'headphones listen audio', 'słuchawki słuchanie audio'),
  YoEmoji('🎼', 'musical score', 'zapis nutowy', 'music notes', 'muzyka nuty'),
  YoEmoji('🎵', 'musical note', 'nuta', 'music song', 'muzyka piosenka'),
  YoEmoji('🎶', 'musical notes', 'nuty', 'music song', 'muzyka piosenka'),
  YoEmoji('🎹', 'musical keyboard', 'keyboard', 'piano music', 'pianino muzyka'),
  YoEmoji('🥁', 'drum', 'bęben', 'drums music', 'bębny perkusja muzyka'),
  YoEmoji('🎷', 'saxophone', 'saksofon', 'sax music jazz', 'saksofon muzyka jazz'),
  YoEmoji('🎺', 'trumpet', 'trąbka', 'trumpet music', 'trąbka muzyka'),
  YoEmoji('🎸', 'guitar', 'gitara', 'guitar music rock', 'gitara muzyka rock'),
  YoEmoji('🎻', 'violin', 'skrzypce', 'violin music', 'skrzypce muzyka'),
  YoEmoji('🎲', 'game die', 'kostka do gry', 'dice game luck', 'kostka gra los'),
  YoEmoji('🎯', 'bullseye', 'tarcza', 'target goal aim', 'cel tarcza'),
  YoEmoji('🎳', 'bowling', 'kręgle', 'bowling', 'kręgle'),
  YoEmoji('🎮', 'video game', 'gra wideo', 'gaming controller', 'gry pad'),
  YoEmoji('🕹️', 'joystick', 'joystick', 'gaming arcade', 'gry automat'),
  YoEmoji('🎰', 'slot machine', 'automat do gier', 'casino gamble', 'kasyno hazard'),
];

const _travel = <YoEmoji>[
  YoEmoji('🚗', 'automobile', 'samochód', 'car drive', 'auto samochód jazda'),
  YoEmoji('🚕', 'taxi', 'taksówka', 'taxi cab', 'taxi taksówka'),
  YoEmoji('🚙', 'sport utility vehicle', 'SUV', 'car suv', 'auto suv'),
  YoEmoji('🚌', 'bus', 'autobus', 'bus transport', 'autobus transport'),
  YoEmoji('🏎️', 'racing car', 'bolid', 'race car fast', 'wyścig szybko'),
  YoEmoji('🚓', 'police car', 'radiowóz', 'police', 'policja'),
  YoEmoji('🚑', 'ambulance', 'karetka', 'ambulance emergency', 'karetka pogotowie'),
  YoEmoji('🚒', 'fire engine', 'wóz strażacki', 'fire truck', 'straż pożarna'),
  YoEmoji('🚚', 'delivery truck', 'ciężarówka dostawcza', 'truck delivery', 'ciężarówka dostawa'),
  YoEmoji('🚜', 'tractor', 'traktor', 'tractor farm', 'traktor rolnictwo'),
  YoEmoji('🛴', 'kick scooter', 'hulajnoga', 'scooter', 'hulajnoga'),
  YoEmoji('🚲', 'bicycle', 'rower', 'bike cycle', 'rower'),
  YoEmoji('🛵', 'motor scooter', 'skuter', 'scooter moped', 'skuter motorower'),
  YoEmoji('🏍️', 'motorcycle', 'motocykl', 'motorbike', 'motocykl motor'),
  YoEmoji('🚨', 'police car light', 'kogut policyjny', 'siren emergency alert', 'syrena alarm'),
  YoEmoji('🚅', 'bullet train', 'superszybki pociąg', 'train fast', 'pociąg szybki'),
  YoEmoji('🚆', 'train', 'pociąg', 'train rail', 'pociąg kolej'),
  YoEmoji('🚇', 'metro', 'metro', 'subway metro', 'metro'),
  YoEmoji('🚊', 'tram', 'tramwaj', 'tram', 'tramwaj'),
  YoEmoji('🚉', 'station', 'stacja', 'train station', 'stacja dworzec'),
  YoEmoji('✈️', 'airplane', 'samolot', 'plane fly travel', 'samolot lot podróż'),
  YoEmoji('🛫', 'airplane departure', 'start samolotu', 'takeoff departure', 'start odlot'),
  YoEmoji('🛬', 'airplane arrival', 'lądowanie', 'landing arrival', 'lądowanie przylot'),
  YoEmoji('💺', 'seat', 'fotel', 'seat plane', 'fotel miejsce'),
  YoEmoji('🚁', 'helicopter', 'helikopter', 'helicopter', 'helikopter śmigłowiec'),
  YoEmoji('🚀', 'rocket', 'rakieta', 'rocket launch space fast', 'rakieta start kosmos'),
  YoEmoji('🛸', 'flying saucer', 'latający spodek', 'ufo alien', 'ufo kosmita'),
  YoEmoji('🛶', 'canoe', 'kajak', 'canoe kayak', 'kajak'),
  YoEmoji('⛵', 'sailboat', 'żaglówka', 'sail boat', 'żagle łódka'),
  YoEmoji('🚤', 'speedboat', 'motorówka', 'boat fast', 'łódź motorówka'),
  YoEmoji('⛴️', 'ferry', 'prom', 'ferry boat', 'prom'),
  YoEmoji('🚢', 'ship', 'statek', 'ship cruise', 'statek rejs'),
  YoEmoji('⚓', 'anchor', 'kotwica', 'anchor sea', 'kotwica morze'),
  YoEmoji('🚧', 'construction', 'roboty drogowe', 'construction barrier', 'budowa remont'),
  YoEmoji('🗺️', 'world map', 'mapa świata', 'map travel', 'mapa podróż'),
  YoEmoji('🗿', 'moai', 'moai', 'statue stone', 'posąg kamień'),
  YoEmoji('🗽', 'Statue of Liberty', 'Statua Wolności', 'new york usa', 'nowy jork usa'),
  YoEmoji('🗼', 'Tokyo tower', 'wieża Tokyo', 'tokyo japan', 'tokio japonia'),
  YoEmoji('🏰', 'castle', 'zamek', 'castle fairy', 'zamek baśń'),
  YoEmoji('🏟️', 'stadium', 'stadion', 'stadium sport', 'stadion sport'),
  YoEmoji('🎡', 'ferris wheel', 'diabelski młyn', 'fair amusement', 'wesołe miasteczko'),
  YoEmoji('🎢', 'roller coaster', 'kolejka górska', 'amusement ride', 'wesołe miasteczko'),
  YoEmoji('🎠', 'carousel horse', 'karuzela', 'carousel fair', 'karuzela'),
  YoEmoji('⛲', 'fountain', 'fontanna', 'fountain park', 'fontanna park'),
  YoEmoji('⛱️', 'umbrella on ground', 'parasol plażowy', 'beach summer', 'plaża lato'),
  YoEmoji('🏖️', 'beach with umbrella', 'plaża', 'beach holiday summer', 'plaża wakacje lato'),
  YoEmoji('🏝️', 'desert island', 'bezludna wyspa', 'island holiday', 'wyspa wakacje'),
  YoEmoji('🏜️', 'desert', 'pustynia', 'desert sand', 'pustynia piasek'),
  YoEmoji('🌋', 'volcano', 'wulkan', 'volcano eruption', 'wulkan erupcja'),
  YoEmoji('⛰️', 'mountain', 'góra', 'mountain hike', 'góra wędrówka'),
  YoEmoji('🏔️', 'snow-capped mountain', 'ośnieżona góra', 'mountain snow', 'góra śnieg'),
  YoEmoji('🏕️', 'camping', 'kemping', 'camp tent outdoors', 'kemping namiot'),
  YoEmoji('⛺', 'tent', 'namiot', 'camp tent', 'namiot kemping'),
  YoEmoji('🏠', 'house', 'dom', 'home house', 'dom'),
  YoEmoji('🏡', 'house with garden', 'dom z ogrodem', 'home garden', 'dom ogród'),
  YoEmoji('🏢', 'office building', 'biurowiec', 'office work', 'biuro praca'),
  YoEmoji('🏥', 'hospital', 'szpital', 'hospital health', 'szpital zdrowie'),
  YoEmoji('🏦', 'bank', 'bank', 'bank money', 'bank pieniądze'),
  YoEmoji('🏨', 'hotel', 'hotel', 'hotel travel', 'hotel podróż'),
  YoEmoji('🏫', 'school', 'szkoła', 'school study', 'szkoła nauka'),
  YoEmoji('🏭', 'factory', 'fabryka', 'factory industry', 'fabryka przemysł'),
  YoEmoji('🏛️', 'classical building', 'budowla klasyczna', 'museum bank', 'muzeum'),
  YoEmoji('⛪', 'church', 'kościół', 'church religion', 'kościół religia'),
  YoEmoji('🕌', 'mosque', 'meczet', 'mosque religion', 'meczet religia'),
  YoEmoji('🕍', 'synagogue', 'synagoga', 'synagogue religion', 'synagoga religia'),
  YoEmoji('🌃', 'night with stars', 'gwiaździsta noc', 'night city', 'noc miasto'),
  YoEmoji('🏙️', 'cityscape', 'panorama miasta', 'city skyline', 'miasto panorama'),
  YoEmoji('🌄', 'sunrise over mountains', 'wschód nad górami', 'sunrise morning', 'wschód poranek'),
  YoEmoji('🌅', 'sunrise', 'wschód słońca', 'sunrise morning', 'wschód poranek'),
  YoEmoji('🌆', 'cityscape at dusk', 'miasto o zmierzchu', 'city evening', 'miasto wieczór'),
  YoEmoji('🌇', 'sunset', 'zachód słońca', 'sunset evening', 'zachód wieczór'),
  YoEmoji('🌉', 'bridge at night', 'most nocą', 'bridge night', 'most noc'),
  YoEmoji('♨️', 'hot springs', 'gorące źródła', 'spa hot', 'spa gorąco'),
  YoEmoji('🎇', 'sparkler', 'zimne ognie', 'sparkler celebrate', 'zimne ognie świętowanie'),
  YoEmoji('🎆', 'fireworks', 'fajerwerki', 'fireworks celebrate new year', 'fajerwerki sylwester'),
  YoEmoji('🌌', 'milky way', 'droga mleczna', 'space stars galaxy', 'kosmos gwiazdy galaktyka'),
  YoEmoji('🌠', 'shooting star', 'spadająca gwiazda', 'wish star', 'życzenie gwiazda'),
  YoEmoji('🌍', 'globe showing Europe-Africa', 'kula ziemska Europa i Afryka', 'earth world globe', 'ziemia świat glob'),
  YoEmoji('🌎', 'globe showing Americas', 'kula ziemska Ameryki', 'earth world globe', 'ziemia świat glob'),
  YoEmoji('🌏', 'globe showing Asia-Australia', 'kula ziemska Azja i Australia', 'earth world globe', 'ziemia świat glob'),
  YoEmoji('🌐', 'globe with meridians', 'globus z południkami', 'internet web world', 'internet sieć świat'),
  YoEmoji('🌑', 'new moon', 'nów', 'moon dark', 'księżyc nów'),
  YoEmoji('🌓', 'first quarter moon', 'pierwsza kwadra', 'moon', 'księżyc kwadra'),
  YoEmoji('🌕', 'full moon', 'pełnia', 'moon full', 'księżyc pełnia'),
  YoEmoji('🌙', 'crescent moon', 'sierp księżyca', 'moon night', 'księżyc noc'),
  YoEmoji('🌚', 'new moon face', 'twarz nowiu', 'moon face', 'księżyc twarz'),
  YoEmoji('🌝', 'full moon face', 'twarz pełni', 'moon face', 'księżyc twarz'),
  YoEmoji('🌞', 'sun with face', 'słońce z twarzą', 'sun face', 'słońce twarz'),
  YoEmoji('⭐', 'star', 'gwiazda', 'star favourite', 'gwiazda ulubione'),
  YoEmoji('🌟', 'glowing star', 'świecąca gwiazda', 'star shine', 'gwiazda blask'),
  YoEmoji('✨', 'sparkles', 'iskierki', 'sparkle shine magic new', 'blask magia nowe iskry'),
  YoEmoji('⚡', 'high voltage', 'wysokie napięcie', 'lightning power fast', 'błyskawica moc'),
  YoEmoji('☄️', 'comet', 'kometa', 'comet space', 'kometa kosmos'),
  YoEmoji('🔥', 'fire', 'ogień', 'fire hot lit flame', 'ogień gorąco płomień'),
  YoEmoji('🌈', 'rainbow', 'tęcza', 'rainbow pride colour', 'tęcza kolory'),
  YoEmoji('☀️', 'sun', 'słońce', 'sun sunny weather', 'słońce pogoda'),
  YoEmoji('⛅', 'sun behind cloud', 'słońce za chmurą', 'weather cloudy', 'pogoda pochmurno'),
  YoEmoji('☁️', 'cloud', 'chmura', 'cloud weather', 'chmura pogoda'),
  YoEmoji('🌧️', 'cloud with rain', 'deszcz', 'rain weather', 'deszcz pogoda'),
  YoEmoji('⛈️', 'cloud with lightning and rain', 'burza', 'storm weather', 'burza pogoda'),
  YoEmoji('🌨️', 'cloud with snow', 'śnieg z chmury', 'snow weather', 'śnieg pogoda'),
  YoEmoji('❄️', 'snowflake', 'płatek śniegu', 'snow winter cold', 'śnieg zima zimno'),
  YoEmoji('☃️', 'snowman', 'bałwan', 'snow winter', 'bałwan zima'),
  YoEmoji('⛄', 'snowman without snow', 'bałwanek', 'snow winter', 'bałwan zima'),
  YoEmoji('🌬️', 'wind face', 'wiatr', 'wind weather', 'wiatr pogoda'),
  YoEmoji('🌪️', 'tornado', 'tornado', 'tornado storm', 'tornado burza'),
  YoEmoji('🌫️', 'fog', 'mgła', 'fog weather', 'mgła pogoda'),
  YoEmoji('🌊', 'water wave', 'fala', 'wave sea ocean', 'fala morze ocean'),
  YoEmoji('💧', 'droplet', 'kropla', 'water drop', 'woda kropla'),
  YoEmoji('☔', 'umbrella with rain drops', 'parasol z deszczem', 'rain umbrella', 'deszcz parasol'),
];

const _objects = <YoEmoji>[
  YoEmoji('⌚', 'watch', 'zegarek', 'time watch', 'czas zegarek'),
  YoEmoji('📱', 'mobile phone', 'telefon', 'phone mobile', 'telefon komórka'),
  YoEmoji('💻', 'laptop', 'laptop', 'computer laptop work', 'komputer laptop praca'),
  YoEmoji('⌨️', 'keyboard', 'klawiatura', 'keyboard type', 'klawiatura pisanie'),
  YoEmoji('🖥️', 'desktop computer', 'komputer stacjonarny', 'computer monitor', 'komputer monitor'),
  YoEmoji('🖨️', 'printer', 'drukarka', 'print', 'drukarka'),
  YoEmoji('🖱️', 'computer mouse', 'myszka', 'mouse click', 'myszka klik'),
  YoEmoji('💾', 'floppy disk', 'dyskietka', 'save disk', 'zapis dyskietka'),
  YoEmoji('💿', 'optical disk', 'płyta', 'cd disk', 'płyta cd'),
  YoEmoji('📷', 'camera', 'aparat', 'camera photo', 'aparat zdjęcie'),
  YoEmoji('📸', 'camera with flash', 'aparat z lampą', 'camera photo flash', 'aparat zdjęcie lampa'),
  YoEmoji('📹', 'video camera', 'kamera', 'video record', 'wideo nagrywanie'),
  YoEmoji('🎥', 'movie camera', 'kamera filmowa', 'movie film', 'film kino'),
  YoEmoji('📽️', 'film projector', 'projektor', 'film projector', 'projektor film'),
  YoEmoji('📞', 'telephone receiver', 'słuchawka telefonu', 'call phone', 'rozmowa telefon'),
  YoEmoji('☎️', 'telephone', 'telefon stacjonarny', 'phone call', 'telefon rozmowa'),
  YoEmoji('📠', 'fax machine', 'faks', 'fax', 'faks'),
  YoEmoji('📺', 'television', 'telewizor', 'tv watch', 'telewizor oglądanie'),
  YoEmoji('📻', 'radio', 'radio', 'radio music', 'radio muzyka'),
  YoEmoji('🎙️', 'studio microphone', 'mikrofon studyjny', 'podcast mic record voice', 'podcast mikrofon nagranie głos'),
  YoEmoji('🎚️', 'level slider', 'suwak', 'audio mix', 'audio miks'),
  YoEmoji('🎛️', 'control knobs', 'pokrętła', 'audio mix', 'audio miks'),
  YoEmoji('⏱️', 'stopwatch', 'stoper', 'timer stopwatch', 'stoper czas'),
  YoEmoji('⏲️', 'timer clock', 'minutnik', 'timer', 'minutnik'),
  YoEmoji('⏰', 'alarm clock', 'budzik', 'alarm wake time', 'budzik czas'),
  YoEmoji('⌛', 'hourglass done', 'klepsydra', 'time wait', 'czas czekanie'),
  YoEmoji('⏳', 'hourglass not done', 'klepsydra sypiąca', 'time wait loading', 'czas czekanie'),
  YoEmoji('📡', 'satellite antenna', 'antena satelitarna', 'satellite signal', 'antena sygnał'),
  YoEmoji('🔋', 'battery', 'bateria', 'battery power', 'bateria zasilanie'),
  YoEmoji('🔌', 'electric plug', 'wtyczka', 'plug power', 'wtyczka prąd'),
  YoEmoji('💡', 'light bulb', 'żarówka', 'idea light', 'pomysł światło'),
  YoEmoji('🔦', 'flashlight', 'latarka', 'torch light', 'latarka światło'),
  YoEmoji('🕯️', 'candle', 'świeca', 'candle light', 'świeca światło'),
  YoEmoji('🗑️', 'wastebasket', 'kosz', 'trash delete bin', 'kosz usuń śmieci'),
  YoEmoji('💸', 'money with wings', 'pieniądze ze skrzydłami', 'money spend', 'pieniądze wydatek'),
  YoEmoji('💵', 'dollar banknote', 'banknot dolarowy', 'money dollar cash', 'pieniądze dolar gotówka'),
  YoEmoji('💶', 'euro banknote', 'banknot euro', 'money euro cash', 'pieniądze euro gotówka'),
  YoEmoji('💰', 'money bag', 'worek pieniędzy', 'money rich', 'pieniądze bogactwo'),
  YoEmoji('💳', 'credit card', 'karta płatnicza', 'card pay', 'karta płatność'),
  YoEmoji('💎', 'gem stone', 'diament', 'diamond gem', 'diament klejnot'),
  YoEmoji('⚖️', 'balance scale', 'waga', 'justice law balance', 'sprawiedliwość prawo'),
  YoEmoji('🔧', 'wrench', 'klucz płaski', 'tool fix', 'narzędzie naprawa'),
  YoEmoji('🔨', 'hammer', 'młotek', 'tool build', 'narzędzie budowa'),
  YoEmoji('🛠️', 'hammer and wrench', 'narzędzia', 'tools fix settings', 'narzędzia naprawa'),
  YoEmoji('🔩', 'nut and bolt', 'śruba', 'bolt tool', 'śruba narzędzie'),
  YoEmoji('⚙️', 'gear', 'zębatka', 'settings gear', 'ustawienia zębatka'),
  YoEmoji('⛓️', 'chains', 'łańcuchy', 'chain link', 'łańcuch ogniwo'),
  YoEmoji('💊', 'pill', 'tabletka', 'medicine pill', 'lek tabletka'),
  YoEmoji('💉', 'syringe', 'strzykawka', 'injection vaccine', 'zastrzyk szczepionka'),
  YoEmoji('🚪', 'door', 'drzwi', 'door exit', 'drzwi wyjście'),
  YoEmoji('🛏️', 'bed', 'łóżko', 'bed sleep', 'łóżko sen'),
  YoEmoji('🛋️', 'couch and lamp', 'kanapa', 'sofa relax', 'kanapa relaks'),
  YoEmoji('🚿', 'shower', 'prysznic', 'shower bath', 'prysznic kąpiel'),
  YoEmoji('🛁', 'bathtub', 'wanna', 'bath', 'wanna kąpiel'),
  YoEmoji('🔑', 'key', 'klucz', 'key unlock', 'klucz otwieranie'),
  YoEmoji('🗝️', 'old key', 'stary klucz', 'key secret', 'klucz sekret'),
  YoEmoji('📦', 'package', 'paczka', 'box parcel delivery', 'pudełko paczka dostawa'),
  YoEmoji('📫', 'closed mailbox with raised flag', 'skrzynka pocztowa', 'mail post', 'poczta skrzynka'),
  YoEmoji('📮', 'postbox', 'skrzynka nadawcza', 'mail post', 'poczta'),
  YoEmoji('✉️', 'envelope', 'koperta', 'mail letter email', 'poczta list e-mail'),
  YoEmoji('📧', 'e-mail', 'e-mail', 'email mail', 'e-mail poczta'),
  YoEmoji('📨', 'incoming envelope', 'wiadomość przychodząca', 'mail receive', 'poczta odbiór'),
  YoEmoji('📩', 'envelope with arrow', 'wysłana wiadomość', 'mail send', 'poczta wysyłka'),
  YoEmoji('📝', 'memo', 'notatka', 'note write memo', 'notatka pisanie'),
  YoEmoji('✏️', 'pencil', 'ołówek', 'write edit pencil', 'pisanie edycja ołówek'),
  YoEmoji('🖊️', 'pen', 'długopis', 'write pen', 'pisanie długopis'),
  YoEmoji('🖌️', 'paintbrush', 'pędzel', 'paint art', 'malowanie sztuka'),
  YoEmoji('🖍️', 'crayon', 'kredka', 'draw colour', 'rysowanie kolor'),
  YoEmoji('📄', 'page facing up', 'kartka', 'document page', 'dokument strona'),
  YoEmoji('📑', 'bookmark tabs', 'zakładki', 'bookmark tabs', 'zakładki'),
  YoEmoji('📊', 'bar chart', 'wykres słupkowy', 'chart stats data', 'wykres statystyki dane'),
  YoEmoji('📈', 'chart increasing', 'wykres rosnący', 'growth up stats', 'wzrost statystyki'),
  YoEmoji('📉', 'chart decreasing', 'wykres malejący', 'decline down stats', 'spadek statystyki'),
  YoEmoji('📋', 'clipboard', 'schowek', 'clipboard copy list', 'schowek kopiuj lista'),
  YoEmoji('📌', 'pushpin', 'pinezka', 'pin', 'pinezka przypnij'),
  YoEmoji('📎', 'paperclip', 'spinacz', 'attach clip', 'załącznik spinacz'),
  YoEmoji('✂️', 'scissors', 'nożyczki', 'cut scissors', 'wytnij nożyczki'),
  YoEmoji('📁', 'file folder', 'folder', 'folder file', 'folder plik'),
  YoEmoji('📅', 'calendar', 'kalendarz', 'date calendar', 'data kalendarz'),
  YoEmoji('📆', 'tear-off calendar', 'kalendarz z kartkami', 'date calendar', 'data kalendarz'),
  YoEmoji('📖', 'open book', 'otwarta książka', 'book read', 'książka czytanie'),
  YoEmoji('📚', 'books', 'książki', 'books study read', 'książki nauka czytanie'),
  YoEmoji('📓', 'notebook', 'zeszyt', 'notebook write', 'zeszyt pisanie'),
  YoEmoji('🔖', 'bookmark', 'zakładka', 'bookmark save', 'zakładka zapisz'),
  YoEmoji('🏷️', 'label', 'etykieta', 'tag label', 'tag etykieta'),
  YoEmoji('🔍', 'magnifying glass tilted left', 'lupa', 'search find zoom', 'szukaj znajdź lupa'),
  YoEmoji('🔎', 'magnifying glass tilted right', 'lupa w prawo', 'search find', 'szukaj znajdź'),
  YoEmoji('🔐', 'locked with key', 'zamknięte na klucz', 'lock secure', 'zamek bezpieczeństwo'),
  YoEmoji('🔒', 'locked', 'kłódka zamknięta', 'lock private secure', 'zamek prywatne'),
  YoEmoji('🔓', 'unlocked', 'kłódka otwarta', 'unlock open', 'otwarte'),
  YoEmoji('🔔', 'bell', 'dzwonek', 'bell notification alert', 'dzwonek powiadomienie'),
  YoEmoji('🔕', 'bell with slash', 'wyciszony dzwonek', 'mute silent', 'wyciszenie'),
  YoEmoji('📢', 'loudspeaker', 'megafon', 'announce loud', 'ogłoszenie głośno'),
  YoEmoji('📣', 'megaphone', 'megafon ręczny', 'announce shout', 'ogłoszenie krzyk'),
  YoEmoji('🔮', 'crystal ball', 'kryształowa kula', 'magic future', 'magia przyszłość'),
  YoEmoji('🎁', 'wrapped gift', 'prezent', 'gift present birthday', 'prezent urodziny'),
  YoEmoji('🎈', 'balloon', 'balon', 'balloon party', 'balon impreza'),
  YoEmoji('🎉', 'party popper', 'konfetti', 'party celebrate congrats', 'impreza świętowanie gratulacje'),
  YoEmoji('🎊', 'confetti ball', 'kula konfetti', 'party celebrate', 'impreza świętowanie'),
  YoEmoji('🎀', 'ribbon', 'kokarda', 'ribbon gift', 'kokarda prezent'),
  YoEmoji('🎄', 'Christmas tree', 'choinka', 'christmas tree', 'święta choinka'),
  YoEmoji('🎃', 'jack-o-lantern', 'dynia', 'halloween pumpkin', 'halloween dynia'),
  YoEmoji('👑', 'crown', 'korona', 'king queen royal win', 'król królowa korona'),
  YoEmoji('👓', 'glasses', 'okulary', 'glasses see', 'okulary'),
  YoEmoji('🕶️', 'sunglasses', 'okulary przeciwsłoneczne', 'sunglasses cool', 'okulary słońce'),
  YoEmoji('👔', 'necktie', 'krawat', 'tie formal work', 'krawat praca'),
  YoEmoji('👕', 't-shirt', 'koszulka', 'shirt clothes', 'koszulka ubranie'),
  YoEmoji('👖', 'jeans', 'dżinsy', 'jeans clothes', 'dżinsy ubranie'),
  YoEmoji('👗', 'dress', 'sukienka', 'dress clothes', 'sukienka ubranie'),
  YoEmoji('👙', 'bikini', 'bikini', 'bikini beach', 'bikini plaża'),
  YoEmoji('👘', 'kimono', 'kimono', 'kimono japan', 'kimono japonia'),
  YoEmoji('👠', 'high-heeled shoe', 'szpilki', 'shoes heels', 'buty szpilki'),
  YoEmoji('👟', 'running shoe', 'but sportowy', 'shoes sneakers sport', 'buty sportowe'),
  YoEmoji('🎒', 'backpack', 'plecak', 'bag school', 'plecak szkoła'),
  YoEmoji('👜', 'handbag', 'torebka', 'bag purse', 'torebka'),
  YoEmoji('💼', 'briefcase', 'teczka', 'work business bag', 'praca biznes teczka'),
  YoEmoji('☂️', 'umbrella', 'parasol', 'umbrella rain', 'parasol deszcz'),
];

const _symbols = <YoEmoji>[
  YoEmoji('✅', 'check mark button', 'zaznaczone', 'yes done ok tick', 'tak gotowe ok'),
  YoEmoji('✔️', 'check mark', 'ptaszek', 'yes done tick', 'tak gotowe'),
  YoEmoji('☑️', 'check box with check', 'zaznaczony kwadrat', 'checkbox done', 'zaznaczone'),
  YoEmoji('❌', 'cross mark', 'krzyżyk', 'no wrong cancel', 'nie błąd anuluj'),
  YoEmoji('❎', 'cross mark button', 'przycisk krzyżyka', 'no cancel', 'nie anuluj'),
  YoEmoji('➕', 'plus', 'plus', 'add plus', 'dodaj plus'),
  YoEmoji('➖', 'minus', 'minus', 'remove minus', 'usuń minus'),
  YoEmoji('➗', 'divide', 'znak dzielenia', 'divide math', 'dzielenie matematyka'),
  YoEmoji('✖️', 'multiply', 'znak mnożenia', 'multiply math', 'mnożenie matematyka'),
  YoEmoji('‼️', 'double exclamation mark', 'podwójny wykrzyknik', 'important', 'ważne'),
  YoEmoji('⁉️', 'exclamation question mark', 'wykrzyknik i pytajnik', 'what surprise', 'co zdziwienie'),
  YoEmoji('❓', 'question mark', 'pytajnik', 'question help', 'pytanie pomoc'),
  YoEmoji('❗', 'exclamation mark', 'wykrzyknik', 'important warning', 'ważne uwaga'),
  YoEmoji('⚠️', 'warning', 'ostrzeżenie', 'warning caution alert', 'ostrzeżenie uwaga'),
  YoEmoji('🚸', 'children crossing', 'przejście dla dzieci', 'children crossing', 'dzieci przejście'),
  YoEmoji('🔞', 'no one under eighteen', 'od 18 lat', 'adult 18', 'dorośli 18'),
  YoEmoji('☢️', 'radioactive', 'znak radioaktywności', 'radiation danger', 'promieniowanie'),
  YoEmoji('☣️', 'biohazard', 'zagrożenie biologiczne', 'biohazard danger', 'zagrożenie'),
  YoEmoji('🚫', 'prohibited', 'zakaz', 'no forbidden ban', 'zakaz zabronione'),
  YoEmoji('⛔', 'no entry', 'zakaz wjazdu', 'stop no entry', 'stop zakaz'),
  YoEmoji('⬆️', 'up arrow', 'strzałka w górę', 'arrow up', 'strzałka góra'),
  YoEmoji('⬇️', 'down arrow', 'strzałka w dół', 'arrow down', 'strzałka dół'),
  YoEmoji('⬅️', 'left arrow', 'strzałka w lewo', 'arrow left back', 'strzałka lewo wstecz'),
  YoEmoji('➡️', 'right arrow', 'strzałka w prawo', 'arrow right next', 'strzałka prawo dalej'),
  YoEmoji('↕️', 'up-down arrow', 'strzałka góra-dół', 'arrow', 'strzałka'),
  YoEmoji('↔️', 'left-right arrow', 'strzałka lewo-prawo', 'arrow', 'strzałka'),
  YoEmoji('🔄', 'counterclockwise arrows button', 'strzałki odświeżania', 'refresh reload sync', 'odśwież synchronizacja'),
  YoEmoji('🔙', 'BACK arrow', 'strzałka BACK', 'back', 'wstecz'),
  YoEmoji('🔝', 'TOP arrow', 'strzałka TOP', 'top up', 'góra'),
  YoEmoji('🔀', 'shuffle tracks button', 'losowe odtwarzanie', 'shuffle random music', 'losowo muzyka'),
  YoEmoji('🔁', 'repeat button', 'powtarzanie', 'repeat loop', 'powtarzaj pętla'),
  YoEmoji('▶️', 'play button', 'odtwórz', 'play start', 'odtwórz start'),
  YoEmoji('⏸️', 'pause button', 'pauza', 'pause', 'pauza'),
  YoEmoji('⏹️', 'stop button', 'stop', 'stop', 'stop'),
  YoEmoji('⏺️', 'record button', 'nagrywanie', 'record', 'nagrywanie'),
  YoEmoji('⏭️', 'next track button', 'następny utwór', 'next skip', 'następny'),
  YoEmoji('⏮️', 'last track button', 'poprzedni utwór', 'previous back', 'poprzedni'),
  YoEmoji('⏩', 'fast-forward button', 'przewijanie do przodu', 'forward fast', 'przewijanie'),
  YoEmoji('⏪', 'fast reverse button', 'przewijanie do tyłu', 'rewind back', 'przewijanie'),
  YoEmoji('📶', 'antenna bars', 'zasięg', 'signal network', 'sygnał sieć'),
  YoEmoji('📳', 'vibration mode', 'tryb wibracji', 'vibrate phone', 'wibracje telefon'),
  YoEmoji('📴', 'mobile phone off', 'telefon wyłączony', 'phone off', 'telefon wyłączony'),
  YoEmoji('♀️', 'female sign', 'znak kobiety', 'female woman', 'kobieta'),
  YoEmoji('♂️', 'male sign', 'znak mężczyzny', 'male man', 'mężczyzna'),
  YoEmoji('♻️', 'recycling symbol', 'symbol recyklingu', 'recycle green', 'recykling eko'),
  YoEmoji('🔱', 'trident emblem', 'trójząb', 'trident', 'trójząb'),
  YoEmoji('⚜️', 'fleur-de-lis', 'lilia heraldyczna', 'lily emblem', 'lilia herb'),
  YoEmoji('🔰', 'Japanese symbol for beginner', 'symbol początkującego', 'beginner new', 'początkujący nowy'),
  YoEmoji('⭕', 'hollow red circle', 'czerwone kółko', 'circle correct', 'kółko'),
  YoEmoji('🔘', 'radio button', 'przycisk radiowy', 'button select', 'przycisk wybór'),
  YoEmoji('⚪', 'white circle', 'białe kółko', 'circle white', 'kółko białe'),
  YoEmoji('⚫', 'black circle', 'czarne kółko', 'circle black', 'kółko czarne'),
  YoEmoji('🔴', 'red circle', 'czerwone koło', 'circle red live', 'koło czerwone na żywo'),
  YoEmoji('🔵', 'blue circle', 'niebieskie koło', 'circle blue', 'koło niebieskie'),
  YoEmoji('🔺', 'red triangle pointed up', 'czerwony trójkąt w górę', 'triangle up', 'trójkąt góra'),
  YoEmoji('🔻', 'red triangle pointed down', 'czerwony trójkąt w dół', 'triangle down', 'trójkąt dół'),
  YoEmoji('🔶', 'large orange diamond', 'duży pomarańczowy romb', 'diamond orange', 'romb'),
  YoEmoji('🔷', 'large blue diamond', 'duży niebieski romb', 'diamond blue', 'romb'),
  YoEmoji('⬛', 'black large square', 'czarny kwadrat', 'square black', 'kwadrat'),
  YoEmoji('⬜', 'white large square', 'biały kwadrat', 'square white', 'kwadrat'),
  YoEmoji('♠️', 'spade suit', 'pik', 'cards spade', 'karty pik'),
  YoEmoji('♥️', 'heart suit', 'kier', 'cards heart', 'karty kier'),
  YoEmoji('♦️', 'diamond suit', 'karo', 'cards diamond', 'karty karo'),
  YoEmoji('♣️', 'club suit', 'trefl', 'cards club', 'karty trefl'),
  YoEmoji('🃏', 'joker', 'joker', 'cards joker', 'karty joker'),
  YoEmoji('💠', 'diamond with a dot', 'romb z kropką', 'diamond', 'romb'),
  YoEmoji('✳️', 'eight-spoked asterisk', 'gwiazdka ośmioramienna', 'asterisk star', 'gwiazdka'),
  YoEmoji('❇️', 'sparkle', 'iskra', 'sparkle new', 'iskra nowe'),
  YoEmoji('™️', 'trade mark', 'znak towarowy', 'trademark tm', 'znak towarowy'),
  YoEmoji('©️', 'copyright', 'prawa autorskie', 'copyright', 'prawa autorskie'),
  YoEmoji('®️', 'registered', 'znak zastrzeżony', 'registered', 'zastrzeżony'),
  YoEmoji('#️⃣', 'keycap hash', 'klawisz krzyżyka', 'hash number', 'hasz numer'),
  YoEmoji('0️⃣', 'keycap 0', 'klawisz 0', 'zero number', 'zero liczba'),
  YoEmoji('1️⃣', 'keycap 1', 'klawisz 1', 'one number', 'jeden liczba'),
  YoEmoji('2️⃣', 'keycap 2', 'klawisz 2', 'two number', 'dwa liczba'),
  YoEmoji('3️⃣', 'keycap 3', 'klawisz 3', 'three number', 'trzy liczba'),
  YoEmoji('4️⃣', 'keycap 4', 'klawisz 4', 'four number', 'cztery liczba'),
  YoEmoji('5️⃣', 'keycap 5', 'klawisz 5', 'five number', 'pięć liczba'),
  YoEmoji('💲', 'heavy dollar sign', 'znak dolara', 'dollar money', 'dolar pieniądze'),
  YoEmoji('💱', 'currency exchange', 'wymiana walut', 'exchange currency', 'wymiana waluta'),
  YoEmoji('♈', 'Aries', 'Baran', 'zodiac star sign', 'zodiak znak'),
  YoEmoji('♉', 'Taurus', 'Byk', 'zodiac star sign', 'zodiak znak'),
  YoEmoji('♊', 'Gemini', 'Bliźnięta', 'zodiac star sign', 'zodiak znak'),
  YoEmoji('♋', 'Cancer', 'Rak', 'zodiac star sign', 'zodiak znak'),
  YoEmoji('♌', 'Leo', 'Lew', 'zodiac star sign', 'zodiak znak'),
  YoEmoji('♍', 'Virgo', 'Panna', 'zodiac star sign', 'zodiak znak'),
  YoEmoji('♎', 'Libra', 'Waga', 'zodiac star sign', 'zodiak znak'),
  YoEmoji('♏', 'Scorpio', 'Skorpion', 'zodiac star sign', 'zodiak znak'),
  YoEmoji('♐', 'Sagittarius', 'Strzelec', 'zodiac star sign', 'zodiak znak'),
  YoEmoji('♑', 'Capricorn', 'Koziorożec', 'zodiac star sign', 'zodiak znak'),
  YoEmoji('♒', 'Aquarius', 'Wodnik', 'zodiac star sign', 'zodiak znak'),
  YoEmoji('♓', 'Pisces', 'Ryby', 'zodiac star sign', 'zodiak znak'),
  YoEmoji('🆗', 'OK button', 'przycisk OK', 'ok agree', 'ok zgoda'),
  YoEmoji('🆕', 'NEW button', 'przycisk NEW', 'new', 'nowe'),
  YoEmoji('🆒', 'COOL button', 'przycisk COOL', 'cool', 'fajne'),
  YoEmoji('🆓', 'FREE button', 'przycisk FREE', 'free', 'darmowe'),
  YoEmoji('🆙', 'UP button', 'przycisk UP', 'up new', 'góra nowe'),
  YoEmoji('ℹ️', 'information', 'informacja', 'info help', 'informacja pomoc'),
];

const _flags = <YoEmoji>[
  YoEmoji('🏁', 'chequered flag', 'flaga w szachownicę', 'race finish', 'wyścig meta'),
  YoEmoji('🚩', 'triangular flag', 'chorągiewka', 'flag mark', 'flaga oznaczenie'),
  YoEmoji('🏳️', 'white flag', 'biała flaga', 'surrender peace', 'poddanie pokój'),
  YoEmoji('🏴', 'black flag', 'czarna flaga', 'flag', 'flaga'),
  YoEmoji('🏳️‍🌈', 'rainbow flag', 'tęczowa flaga', 'pride lgbt rainbow', 'duma lgbt tęcza'),
  YoEmoji('🇵🇱', 'flag of Poland', 'flaga Polski', 'poland polish', 'polska'),
  YoEmoji('🇬🇧', 'flag of the United Kingdom', 'flaga Wielkiej Brytanii', 'uk britain english', 'wielka brytania anglia'),
  YoEmoji('🇺🇸', 'flag of the United States', 'flaga Stanów Zjednoczonych', 'usa america', 'usa ameryka'),
  YoEmoji('🇩🇪', 'flag of Germany', 'flaga Niemiec', 'germany german', 'niemcy'),
  YoEmoji('🇫🇷', 'flag of France', 'flaga Francji', 'france french', 'francja'),
  YoEmoji('🇪🇸', 'flag of Spain', 'flaga Hiszpanii', 'spain spanish', 'hiszpania'),
  YoEmoji('🇮🇹', 'flag of Italy', 'flaga Włoch', 'italy italian', 'włochy'),
  YoEmoji('🇵🇹', 'flag of Portugal', 'flaga Portugalii', 'portugal', 'portugalia'),
  YoEmoji('🇧🇷', 'flag of Brazil', 'flaga Brazylii', 'brazil', 'brazylia'),
  YoEmoji('🇳🇱', 'flag of the Netherlands', 'flaga Holandii', 'netherlands dutch', 'holandia niderlandy'),
  YoEmoji('🇧🇪', 'flag of Belgium', 'flaga Belgii', 'belgium', 'belgia'),
  YoEmoji('🇨🇿', 'flag of Czechia', 'flaga Czech', 'czech', 'czechy'),
  YoEmoji('🇸🇰', 'flag of Slovakia', 'flaga Słowacji', 'slovakia', 'słowacja'),
  YoEmoji('🇺🇦', 'flag of Ukraine', 'flaga Ukrainy', 'ukraine', 'ukraina'),
  YoEmoji('🇱🇹', 'flag of Lithuania', 'flaga Litwy', 'lithuania', 'litwa'),
  YoEmoji('🇱🇻', 'flag of Latvia', 'flaga Łotwy', 'latvia', 'łotwa'),
  YoEmoji('🇪🇪', 'flag of Estonia', 'flaga Estonii', 'estonia', 'estonia'),
  YoEmoji('🇸🇪', 'flag of Sweden', 'flaga Szwecji', 'sweden', 'szwecja'),
  YoEmoji('🇳🇴', 'flag of Norway', 'flaga Norwegii', 'norway', 'norwegia'),
  YoEmoji('🇩🇰', 'flag of Denmark', 'flaga Danii', 'denmark', 'dania'),
  YoEmoji('🇫🇮', 'flag of Finland', 'flaga Finlandii', 'finland', 'finlandia'),
  YoEmoji('🇮🇪', 'flag of Ireland', 'flaga Irlandii', 'ireland', 'irlandia'),
  YoEmoji('🇦🇹', 'flag of Austria', 'flaga Austrii', 'austria', 'austria'),
  YoEmoji('🇨🇭', 'flag of Switzerland', 'flaga Szwajcarii', 'switzerland swiss', 'szwajcaria'),
  YoEmoji('🇬🇷', 'flag of Greece', 'flaga Grecji', 'greece greek', 'grecja'),
  YoEmoji('🇹🇷', 'flag of Türkiye', 'flaga Turcji', 'turkey turkish', 'turcja'),
  YoEmoji('🇷🇴', 'flag of Romania', 'flaga Rumunii', 'romania', 'rumunia'),
  YoEmoji('🇭🇺', 'flag of Hungary', 'flaga Węgier', 'hungary', 'węgry'),
  YoEmoji('🇧🇬', 'flag of Bulgaria', 'flaga Bułgarii', 'bulgaria', 'bułgaria'),
  YoEmoji('🇭🇷', 'flag of Croatia', 'flaga Chorwacji', 'croatia', 'chorwacja'),
  YoEmoji('🇷🇸', 'flag of Serbia', 'flaga Serbii', 'serbia', 'serbia'),
  YoEmoji('🇨🇦', 'flag of Canada', 'flaga Kanady', 'canada', 'kanada'),
  YoEmoji('🇲🇽', 'flag of Mexico', 'flaga Meksyku', 'mexico', 'meksyk'),
  YoEmoji('🇦🇷', 'flag of Argentina', 'flaga Argentyny', 'argentina', 'argentyna'),
  YoEmoji('🇦🇺', 'flag of Australia', 'flaga Australii', 'australia', 'australia'),
  YoEmoji('🇳🇿', 'flag of New Zealand', 'flaga Nowej Zelandii', 'new zealand', 'nowa zelandia'),
  YoEmoji('🇯🇵', 'flag of Japan', 'flaga Japonii', 'japan', 'japonia'),
  YoEmoji('🇰🇷', 'flag of South Korea', 'flaga Korei Południowej', 'korea', 'korea'),
  YoEmoji('🇨🇳', 'flag of China', 'flaga Chin', 'china chinese', 'chiny'),
  YoEmoji('🇮🇳', 'flag of India', 'flaga Indii', 'india', 'indie'),
  YoEmoji('🇮🇩', 'flag of Indonesia', 'flaga Indonezji', 'indonesia', 'indonezja'),
  YoEmoji('🇵🇭', 'flag of the Philippines', 'flaga Filipin', 'philippines', 'filipiny'),
  YoEmoji('🇻🇳', 'flag of Vietnam', 'flaga Wietnamu', 'vietnam', 'wietnam'),
  YoEmoji('🇹🇭', 'flag of Thailand', 'flaga Tajlandii', 'thailand', 'tajlandia'),
  YoEmoji('🇿🇦', 'flag of South Africa', 'flaga RPA', 'south africa', 'rpa afryka'),
  YoEmoji('🇪🇬', 'flag of Egypt', 'flaga Egiptu', 'egypt', 'egipt'),
  YoEmoji('🇳🇬', 'flag of Nigeria', 'flaga Nigerii', 'nigeria', 'nigeria'),
  YoEmoji('🇰🇪', 'flag of Kenya', 'flaga Kenii', 'kenya', 'kenia'),
  YoEmoji('🇮🇱', 'flag of Israel', 'flaga Izraela', 'israel', 'izrael'),
  YoEmoji('🇸🇦', 'flag of Saudi Arabia', 'flaga Arabii Saudyjskiej', 'saudi arabia', 'arabia saudyjska'),
  YoEmoji('🇦🇪', 'flag of the United Arab Emirates', 'flaga Zjednoczonych Emiratów Arabskich', 'uae emirates', 'emiraty zea'),
];

/// Every catalogued emoji, grouped by [YoEmojiCategory] in strip order.
const yoEmojiByCategory = <YoEmojiCategory, List<YoEmoji>>{
  YoEmojiCategory.smileys: _smileys,
  YoEmojiCategory.people: _people,
  YoEmojiCategory.animals: _animals,
  YoEmojiCategory.food: _food,
  YoEmojiCategory.activity: _activity,
  YoEmojiCategory.travel: _travel,
  YoEmojiCategory.objects: _objects,
  YoEmojiCategory.symbols: _symbols,
  YoEmojiCategory.flags: _flags,
};

/// A flat view of the catalogue, in strip order.
final List<YoEmoji> yoEmojiCatalog = List<YoEmoji>.unmodifiable([
  for (final category in YoEmojiCategory.values)
    ...yoEmojiByCategory[category]!,
]);

/// Character-keyed lookup, used to rehydrate persisted "recently used" entries
/// into full [YoEmoji] records with their names and keywords.
final Map<String, YoEmoji> yoEmojiByChar = Map<String, YoEmoji>.unmodifiable({
  for (final emoji in yoEmojiCatalog) emoji.char: emoji,
});

const _polishFolding = <String, String>{
  'ą': 'a',
  'ć': 'c',
  'ę': 'e',
  'ł': 'l',
  'ń': 'n',
  'ó': 'o',
  'ś': 's',
  'ź': 'z',
  'ż': 'z',
};

/// Lowercases and strips Polish diacritics so that "zolw", "żółw" and "Żółw"
/// are the same query. Without this, searching Polish on an English keyboard —
/// which is what most people actually type on — finds nothing.
String yoFoldSearchTerm(String value) {
  final buffer = StringBuffer();
  for (final rune in value.toLowerCase().runes) {
    final character = String.fromCharCode(rune);
    buffer.write(_polishFolding[character] ?? character);
  }
  return buffer.toString();
}

/// Folded haystacks, built once on first search rather than at every keystroke.
final Map<String, String> _searchHaystacks = {
  for (final emoji in yoEmojiCatalog)
    emoji.char: yoFoldSearchTerm(
      '${emoji.name} ${emoji.namePolish} '
      '${emoji.keywords} ${emoji.keywordsPolish}',
    ),
};

/// Emoji whose name or keywords — English or Polish — match [query].
///
/// An empty or whitespace-only query returns the whole catalogue, so the caller
/// can use one code path for "searching" and "browsing".
List<YoEmoji> yoSearchEmoji(String query) {
  final needle = yoFoldSearchTerm(query.trim());
  if (needle.isEmpty) return yoEmojiCatalog;
  return [
    for (final emoji in yoEmojiCatalog)
      if (_searchHaystacks[emoji.char]!.contains(needle)) emoji,
  ];
}
